// Code generated by server-gen. DO NOT EDIT.

package v1

import (
	unsafe "unsafe"

	server "github.com/kubernetes-csi/csi-proxy/integrationtests/apigroups/server"
)

func autoConvert_v1_ComputeDoubleRequest_To_server_ComputeDoubleRequest(in *ComputeDoubleRequest, out *server.ComputeDoubleRequest) error {
	out.Input64 = in.Input64
	return nil
}

// Convert_v1_ComputeDoubleRequest_To_server_ComputeDoubleRequest is an autogenerated conversion function.
func Convert_v1_ComputeDoubleRequest_To_server_ComputeDoubleRequest(in *ComputeDoubleRequest, out *server.ComputeDoubleRequest) error {
	return autoConvert_v1_ComputeDoubleRequest_To_server_ComputeDoubleRequest(in, out)
}

func autoConvert_server_ComputeDoubleResponse_To_v1_ComputeDoubleResponse(in *server.ComputeDoubleResponse, out *ComputeDoubleResponse) error {
	out.Response = in.Response
	return nil
}

// Convert_server_ComputeDoubleResponse_To_v1_ComputeDoubleResponse is an autogenerated conversion function.
func Convert_server_ComputeDoubleResponse_To_v1_ComputeDoubleResponse(in *server.ComputeDoubleResponse, out *ComputeDoubleResponse) error {
	return autoConvert_server_ComputeDoubleResponse_To_v1_ComputeDoubleResponse(in, out)
}

func autoConvert_v1_TellMeAPoemRequest_To_server_TellMeAPoemRequest(in *TellMeAPoemRequest, out *server.TellMeAPoemRequest) error {
	out.IWantATitle = in.IWantATitle
	return nil
}

// Convert_v1_TellMeAPoemRequest_To_server_TellMeAPoemRequest is an autogenerated conversion function.
func Convert_v1_TellMeAPoemRequest_To_server_TellMeAPoemRequest(in *TellMeAPoemRequest, out *server.TellMeAPoemRequest) error {
	return autoConvert_v1_TellMeAPoemRequest_To_server_TellMeAPoemRequest(in, out)
}

func autoConvert_server_TellMeAPoemResponse_To_v1_TellMeAPoemResponse(in *server.TellMeAPoemResponse, out *TellMeAPoemResponse) error {
	out.Title = in.Title
	out.Lines = *(*[]string)(unsafe.Pointer(&in.Lines))
	return nil
}

// Convert_server_TellMeAPoemResponse_To_v1_TellMeAPoemResponse is an autogenerated conversion function.
func Convert_server_TellMeAPoemResponse_To_v1_TellMeAPoemResponse(in *server.TellMeAPoemResponse, out *TellMeAPoemResponse) error {
	return autoConvert_server_TellMeAPoemResponse_To_v1_TellMeAPoemResponse(in, out)
}
