// Code generated by csi-api-gen. DO NOT EDIT.

package internal

import (
	"google.golang.org/grpc"
)

type VersionedAPI interface {
	Register(grpcServer *grpc.Server)
}

// All the functions this group's server needs to define.
type ServerInterface interface {
}
