// Code generated by csi-api-gen. DO NOT EDIT.

package newgroup

import (
	"actual_output/server/new_group/internal"

	"github.com/kubernetes-csi/csi-proxy/internal/server"
)

const name = "new_group"

// ensure the server defines all the required methods
var _ internal.ServerInterface = &Server{}

func (s *Server) VersionedAPIs() []*server.VersionedAPI {

	return []*server.VersionedAPI{}
}
