// +build !ignore_autogenerated

/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by conversion-gen. DO NOT EDIT.

package server

import (
	unsafe "unsafe"

	v1 "github.com/kubernetes-csi/csi-proxy/integrationtests/apigroups/v1"
	conversion "k8s.io/apimachinery/pkg/conversion"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

func init() {
	localSchemeBuilder.Register(RegisterConversions)
}

// RegisterConversions adds conversion functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterConversions(s *runtime.Scheme) error {
	if err := s.AddGeneratedConversionFunc((*ComputeDoubleRequest)(nil), (*v1.ComputeDoubleRequest)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_server_ComputeDoubleRequest_To_v1_ComputeDoubleRequest(a.(*ComputeDoubleRequest), b.(*v1.ComputeDoubleRequest), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1.ComputeDoubleRequest)(nil), (*ComputeDoubleRequest)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_ComputeDoubleRequest_To_server_ComputeDoubleRequest(a.(*v1.ComputeDoubleRequest), b.(*ComputeDoubleRequest), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ComputeDoubleResponse)(nil), (*v1.ComputeDoubleResponse)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_server_ComputeDoubleResponse_To_v1_ComputeDoubleResponse(a.(*ComputeDoubleResponse), b.(*v1.ComputeDoubleResponse), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1.ComputeDoubleResponse)(nil), (*ComputeDoubleResponse)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_ComputeDoubleResponse_To_server_ComputeDoubleResponse(a.(*v1.ComputeDoubleResponse), b.(*ComputeDoubleResponse), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*Server)(nil), (*v1.Server)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_server_Server_To_v1_Server(a.(*Server), b.(*v1.Server), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1.Server)(nil), (*Server)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_Server_To_server_Server(a.(*v1.Server), b.(*Server), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*TellMeAPoemRequest)(nil), (*v1.TellMeAPoemRequest)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_server_TellMeAPoemRequest_To_v1_TellMeAPoemRequest(a.(*TellMeAPoemRequest), b.(*v1.TellMeAPoemRequest), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1.TellMeAPoemRequest)(nil), (*TellMeAPoemRequest)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_TellMeAPoemRequest_To_server_TellMeAPoemRequest(a.(*v1.TellMeAPoemRequest), b.(*TellMeAPoemRequest), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*TellMeAPoemResponse)(nil), (*v1.TellMeAPoemResponse)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_server_TellMeAPoemResponse_To_v1_TellMeAPoemResponse(a.(*TellMeAPoemResponse), b.(*v1.TellMeAPoemResponse), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1.TellMeAPoemResponse)(nil), (*TellMeAPoemResponse)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_TellMeAPoemResponse_To_server_TellMeAPoemResponse(a.(*v1.TellMeAPoemResponse), b.(*TellMeAPoemResponse), scope)
	}); err != nil {
		return err
	}
	return nil
}

func autoConvert_server_ComputeDoubleRequest_To_v1_ComputeDoubleRequest(in *ComputeDoubleRequest, out *v1.ComputeDoubleRequest, s conversion.Scope) error {
	out.Input64 = in.Input64
	return nil
}

// Convert_server_ComputeDoubleRequest_To_v1_ComputeDoubleRequest is an autogenerated conversion function.
func Convert_server_ComputeDoubleRequest_To_v1_ComputeDoubleRequest(in *ComputeDoubleRequest, out *v1.ComputeDoubleRequest, s conversion.Scope) error {
	return autoConvert_server_ComputeDoubleRequest_To_v1_ComputeDoubleRequest(in, out, s)
}

func autoConvert_v1_ComputeDoubleRequest_To_server_ComputeDoubleRequest(in *v1.ComputeDoubleRequest, out *ComputeDoubleRequest, s conversion.Scope) error {
	out.Input64 = in.Input64
	// WARNING: in.XXX_NoUnkeyedLiteral requires manual conversion: does not exist in peer-type
	// WARNING: in.XXX_unrecognized requires manual conversion: does not exist in peer-type
	// WARNING: in.XXX_sizecache requires manual conversion: does not exist in peer-type
	return nil
}

func autoConvert_server_ComputeDoubleResponse_To_v1_ComputeDoubleResponse(in *ComputeDoubleResponse, out *v1.ComputeDoubleResponse, s conversion.Scope) error {
	out.Response = in.Response
	return nil
}

// Convert_server_ComputeDoubleResponse_To_v1_ComputeDoubleResponse is an autogenerated conversion function.
func Convert_server_ComputeDoubleResponse_To_v1_ComputeDoubleResponse(in *ComputeDoubleResponse, out *v1.ComputeDoubleResponse, s conversion.Scope) error {
	return autoConvert_server_ComputeDoubleResponse_To_v1_ComputeDoubleResponse(in, out, s)
}

func autoConvert_v1_ComputeDoubleResponse_To_server_ComputeDoubleResponse(in *v1.ComputeDoubleResponse, out *ComputeDoubleResponse, s conversion.Scope) error {
	out.Response = in.Response
	// WARNING: in.XXX_NoUnkeyedLiteral requires manual conversion: does not exist in peer-type
	// WARNING: in.XXX_unrecognized requires manual conversion: does not exist in peer-type
	// WARNING: in.XXX_sizecache requires manual conversion: does not exist in peer-type
	return nil
}

func autoConvert_server_Server_To_v1_Server(in *Server, out *v1.Server, s conversion.Scope) error {
	return nil
}

// Convert_server_Server_To_v1_Server is an autogenerated conversion function.
func Convert_server_Server_To_v1_Server(in *Server, out *v1.Server, s conversion.Scope) error {
	return autoConvert_server_Server_To_v1_Server(in, out, s)
}

func autoConvert_v1_Server_To_server_Server(in *v1.Server, out *Server, s conversion.Scope) error {
	return nil
}

// Convert_v1_Server_To_server_Server is an autogenerated conversion function.
func Convert_v1_Server_To_server_Server(in *v1.Server, out *Server, s conversion.Scope) error {
	return autoConvert_v1_Server_To_server_Server(in, out, s)
}

func autoConvert_server_TellMeAPoemRequest_To_v1_TellMeAPoemRequest(in *TellMeAPoemRequest, out *v1.TellMeAPoemRequest, s conversion.Scope) error {
	out.IWantATitle = in.IWantATitle
	return nil
}

// Convert_server_TellMeAPoemRequest_To_v1_TellMeAPoemRequest is an autogenerated conversion function.
func Convert_server_TellMeAPoemRequest_To_v1_TellMeAPoemRequest(in *TellMeAPoemRequest, out *v1.TellMeAPoemRequest, s conversion.Scope) error {
	return autoConvert_server_TellMeAPoemRequest_To_v1_TellMeAPoemRequest(in, out, s)
}

func autoConvert_v1_TellMeAPoemRequest_To_server_TellMeAPoemRequest(in *v1.TellMeAPoemRequest, out *TellMeAPoemRequest, s conversion.Scope) error {
	out.IWantATitle = in.IWantATitle
	// WARNING: in.XXX_NoUnkeyedLiteral requires manual conversion: does not exist in peer-type
	// WARNING: in.XXX_unrecognized requires manual conversion: does not exist in peer-type
	// WARNING: in.XXX_sizecache requires manual conversion: does not exist in peer-type
	return nil
}

func autoConvert_server_TellMeAPoemResponse_To_v1_TellMeAPoemResponse(in *TellMeAPoemResponse, out *v1.TellMeAPoemResponse, s conversion.Scope) error {
	out.Title = in.Title
	out.Lines = *(*[]string)(unsafe.Pointer(&in.Lines))
	return nil
}

// Convert_server_TellMeAPoemResponse_To_v1_TellMeAPoemResponse is an autogenerated conversion function.
func Convert_server_TellMeAPoemResponse_To_v1_TellMeAPoemResponse(in *TellMeAPoemResponse, out *v1.TellMeAPoemResponse, s conversion.Scope) error {
	return autoConvert_server_TellMeAPoemResponse_To_v1_TellMeAPoemResponse(in, out, s)
}

func autoConvert_v1_TellMeAPoemResponse_To_server_TellMeAPoemResponse(in *v1.TellMeAPoemResponse, out *TellMeAPoemResponse, s conversion.Scope) error {
	out.Title = in.Title
	out.Lines = *(*[]string)(unsafe.Pointer(&in.Lines))
	// WARNING: in.XXX_NoUnkeyedLiteral requires manual conversion: does not exist in peer-type
	// WARNING: in.XXX_unrecognized requires manual conversion: does not exist in peer-type
	// WARNING: in.XXX_sizecache requires manual conversion: does not exist in peer-type
	return nil
}
