// Code generated by server-gen. DO NOT EDIT.

package v1alpha2

import (
	"github.com/kubernetes-csi/csi-proxy/integrationtests/apigroups/server/dummy/internal"
)

func autoConvert_v1alpha2_ComputeDoubleRequest_To_server_ComputeDoubleRequest(in *ComputeDoubleRequest, out *internal.ComputeDoubleRequest) error {
	out.Input64 = in.Input64
	return nil
}

// Convert_v1alpha2_ComputeDoubleRequest_To_server_ComputeDoubleRequest is an autogenerated conversion function.
func Convert_v1alpha2_ComputeDoubleRequest_To_server_ComputeDoubleRequest(in *ComputeDoubleRequest, out *internal.ComputeDoubleRequest) error {
	return autoConvert_v1alpha2_ComputeDoubleRequest_To_server_ComputeDoubleRequest(in, out)
}

func autoConvert_server_ComputeDoubleResponse_To_v1alpha2_ComputeDoubleResponse(in *internal.ComputeDoubleResponse, out *ComputeDoubleResponse) error {
	out.Response = in.Response
	return nil
}

// Convert_server_ComputeDoubleResponse_To_v1alpha2_ComputeDoubleResponse is an autogenerated conversion function.
func Convert_server_ComputeDoubleResponse_To_v1alpha2_ComputeDoubleResponse(in *internal.ComputeDoubleResponse, out *ComputeDoubleResponse) error {
	return autoConvert_server_ComputeDoubleResponse_To_v1alpha2_ComputeDoubleResponse(in, out)
}
