package v1alpha2

import (
	"context"

	server "github.com/kubernetes-csi/csi-proxy/integrationtests/apigroups/server"
)

// TODO wkpo actually generate that shit...

// TODO wkpo rename to versionedServer, and same below?
type v1Server struct {
	apiGroupServer *server.Server
	// TODO wkpo mouaif...? hard coder en fait, generated...
	version server.Version
}

// TODO wkpo next, apres generation
func (s *v1Server) ComputeDouble(ctx context.Context, v1Request *ComputeDoubleRequest) (*ComputeDoubleResponse, error) {
	request := &server.ComputeDoubleRequest{}
	if err := Convert_v1_ComputeDoubleRequest_To_server_ComputeDoubleRequest(v1Request, request); err != nil {
		return nil, err
	}
	response, err := s.apiGroupServer.ComputeDouble(ctx, request, s.version)
	if err != nil {
		return nil, err
	}
	v1Response := &ComputeDoubleResponse{}
	if err = Convert_server_ComputeDoubleResponse_To_v1_ComputeDoubleResponse(response, v1Response); err != nil {
		return nil, err
	}
	return v1Response, nil
}

func (s *v1Server) TellMeAPoem(ctx context.Context, v1Request *TellMeAPoemRequest) (*TellMeAPoemResponse, error) {
	request := &server.ComputeDoubleRequest{}
	if err := Convert_v1_TellMeAPoemRequest_To_server_TellMeAPoemRequest(v1Request, request); err != nil {
		return nil, err
	}
	response, err := s.apiGroupServer.TellMeAPoem(ctx, request, s.version)
	if err != nil {
		return nil, err
	}
	v1Response := &TellMeAPoemResponse{}
	if err = Convert_server_TellMeAPoemResponse_To_v1_TellMeAPoemResponse(response, v1Response); err != nil {
		return nil, err
	}
	return v1Response, nil
}

// TODO wkpo move to 1st line
// Code generated by server-gen. DO NOT EDIT.
