// Code generated by protoc-gen-go. DO NOT EDIT.
// source: iscsi.proto

package iscsi

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	api "github.com/kubernetes-csi/csi-proxy/api"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type IscsiAuthType int32

const (
	IscsiAuthType_NoAuth     IscsiAuthType = 0
	IscsiAuthType_OneWayCHAP IscsiAuthType = 1
)

var IscsiAuthType_name = map[int32]string{
	0: "NoAuth",
	1: "OneWayCHAP",
}

var IscsiAuthType_value = map[string]int32{
	"NoAuth":     0,
	"OneWayCHAP": 1,
}

func (x IscsiAuthType) String() string {
	return proto.EnumName(IscsiAuthType_name, int32(x))
}

func (IscsiAuthType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_954acfae42d1ccbb, []int{0}
}

// see https://docs.microsoft.com/en-us/windows/desktop/api/iscsidsc/ne-iscsidsc-iscsi_digest_types
type IscsiDigestType int32

const (
	IscsiDigestType_NoDigest IscsiDigestType = 0
	IscsiDigestType_CRC32C   IscsiDigestType = 1
)

var IscsiDigestType_name = map[int32]string{
	0: "NoDigest",
	1: "CRC32C",
}

var IscsiDigestType_value = map[string]int32{
	"NoDigest": 0,
	"CRC32C":   1,
}

func (x IscsiDigestType) String() string {
	return proto.EnumName(IscsiDigestType_name, int32(x))
}

func (IscsiDigestType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_954acfae42d1ccbb, []int{1}
}

type MountISCSILunRequest struct {
	// IQN address
	// follows IQN format: iqn.yyyy-mm.naming-authority:unique name
	NodeIqn string `protobuf:"bytes,1,opt,name=node_iqn,json=nodeIqn,proto3" json:"node_iqn,omitempty"`
	// Authentication Type
	DiscoveryAuthType IscsiAuthType `protobuf:"varint,2,opt,name=discovery_auth_type,json=discoveryAuthType,proto3,enum=IscsiAuthType" json:"discovery_auth_type,omitempty"`
	// Discovery CHAP username
	DiscoveryChapUsername string `protobuf:"bytes,3,opt,name=discovery_chap_username,json=discoveryChapUsername,proto3" json:"discovery_chap_username,omitempty"`
	// Discovery CHAP secret
	DiscoveryChapSecret string        `protobuf:"bytes,4,opt,name=discovery_chap_secret,json=discoveryChapSecret,proto3" json:"discovery_chap_secret,omitempty"`
	SessionAuthType     IscsiAuthType `protobuf:"varint,5,opt,name=session_auth_type,json=sessionAuthType,proto3,enum=IscsiAuthType" json:"session_auth_type,omitempty"`
	// Session CHAP username
	SessionChapUsername string `protobuf:"bytes,6,opt,name=session_chap_username,json=sessionChapUsername,proto3" json:"session_chap_username,omitempty"`
	// Session CHAP secret
	SessionChapSecret string `protobuf:"bytes,7,opt,name=session_chap_secret,json=sessionChapSecret,proto3" json:"session_chap_secret,omitempty"`
	// TargetPortal address
	TargetPortalAddress string `protobuf:"bytes,8,opt,name=target_portal_address,json=targetPortalAddress,proto3" json:"target_portal_address,omitempty"`
	// TargetPortal port
	TargetPortalPort uint32 `protobuf:"varint,9,opt,name=target_portal_port,json=targetPortalPort,proto3" json:"target_portal_port,omitempty"`
	// Readonly mount
	Readonly             bool     `protobuf:"varint,10,opt,name=readonly,proto3" json:"readonly,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MountISCSILunRequest) Reset()         { *m = MountISCSILunRequest{} }
func (m *MountISCSILunRequest) String() string { return proto.CompactTextString(m) }
func (*MountISCSILunRequest) ProtoMessage()    {}
func (*MountISCSILunRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_954acfae42d1ccbb, []int{0}
}

func (m *MountISCSILunRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MountISCSILunRequest.Unmarshal(m, b)
}
func (m *MountISCSILunRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MountISCSILunRequest.Marshal(b, m, deterministic)
}
func (m *MountISCSILunRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MountISCSILunRequest.Merge(m, src)
}
func (m *MountISCSILunRequest) XXX_Size() int {
	return xxx_messageInfo_MountISCSILunRequest.Size(m)
}
func (m *MountISCSILunRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MountISCSILunRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MountISCSILunRequest proto.InternalMessageInfo

func (m *MountISCSILunRequest) GetNodeIqn() string {
	if m != nil {
		return m.NodeIqn
	}
	return ""
}

func (m *MountISCSILunRequest) GetDiscoveryAuthType() IscsiAuthType {
	if m != nil {
		return m.DiscoveryAuthType
	}
	return IscsiAuthType_NoAuth
}

func (m *MountISCSILunRequest) GetDiscoveryChapUsername() string {
	if m != nil {
		return m.DiscoveryChapUsername
	}
	return ""
}

func (m *MountISCSILunRequest) GetDiscoveryChapSecret() string {
	if m != nil {
		return m.DiscoveryChapSecret
	}
	return ""
}

func (m *MountISCSILunRequest) GetSessionAuthType() IscsiAuthType {
	if m != nil {
		return m.SessionAuthType
	}
	return IscsiAuthType_NoAuth
}

func (m *MountISCSILunRequest) GetSessionChapUsername() string {
	if m != nil {
		return m.SessionChapUsername
	}
	return ""
}

func (m *MountISCSILunRequest) GetSessionChapSecret() string {
	if m != nil {
		return m.SessionChapSecret
	}
	return ""
}

func (m *MountISCSILunRequest) GetTargetPortalAddress() string {
	if m != nil {
		return m.TargetPortalAddress
	}
	return ""
}

func (m *MountISCSILunRequest) GetTargetPortalPort() uint32 {
	if m != nil {
		return m.TargetPortalPort
	}
	return 0
}

func (m *MountISCSILunRequest) GetReadonly() bool {
	if m != nil {
		return m.Readonly
	}
	return false
}

type MountISCSILunResponse struct {
	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	// Types that are valid to be assigned to Error:
	//	*MountISCSILunResponse_WindowsApiError
	//	*MountISCSILunResponse_ErrorMessage
	Error                isMountISCSILunResponse_Error `protobuf_oneof:"error"`
	DiskNumber           uint32                        `protobuf:"varint,4,opt,name=disk_number,json=diskNumber,proto3" json:"disk_number,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                      `json:"-"`
	XXX_unrecognized     []byte                        `json:"-"`
	XXX_sizecache        int32                         `json:"-"`
}

func (m *MountISCSILunResponse) Reset()         { *m = MountISCSILunResponse{} }
func (m *MountISCSILunResponse) String() string { return proto.CompactTextString(m) }
func (*MountISCSILunResponse) ProtoMessage()    {}
func (*MountISCSILunResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_954acfae42d1ccbb, []int{1}
}

func (m *MountISCSILunResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MountISCSILunResponse.Unmarshal(m, b)
}
func (m *MountISCSILunResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MountISCSILunResponse.Marshal(b, m, deterministic)
}
func (m *MountISCSILunResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MountISCSILunResponse.Merge(m, src)
}
func (m *MountISCSILunResponse) XXX_Size() int {
	return xxx_messageInfo_MountISCSILunResponse.Size(m)
}
func (m *MountISCSILunResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MountISCSILunResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MountISCSILunResponse proto.InternalMessageInfo

func (m *MountISCSILunResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

type isMountISCSILunResponse_Error interface {
	isMountISCSILunResponse_Error()
}

type MountISCSILunResponse_WindowsApiError struct {
	WindowsApiError *api.WindowsApiError `protobuf:"bytes,2,opt,name=windows_api_error,json=windowsApiError,proto3,oneof"`
}

type MountISCSILunResponse_ErrorMessage struct {
	ErrorMessage string `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3,oneof"`
}

func (*MountISCSILunResponse_WindowsApiError) isMountISCSILunResponse_Error() {}

func (*MountISCSILunResponse_ErrorMessage) isMountISCSILunResponse_Error() {}

func (m *MountISCSILunResponse) GetError() isMountISCSILunResponse_Error {
	if m != nil {
		return m.Error
	}
	return nil
}

func (m *MountISCSILunResponse) GetWindowsApiError() *api.WindowsApiError {
	if x, ok := m.GetError().(*MountISCSILunResponse_WindowsApiError); ok {
		return x.WindowsApiError
	}
	return nil
}

func (m *MountISCSILunResponse) GetErrorMessage() string {
	if x, ok := m.GetError().(*MountISCSILunResponse_ErrorMessage); ok {
		return x.ErrorMessage
	}
	return ""
}

func (m *MountISCSILunResponse) GetDiskNumber() uint32 {
	if m != nil {
		return m.DiskNumber
	}
	return 0
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*MountISCSILunResponse) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*MountISCSILunResponse_WindowsApiError)(nil),
		(*MountISCSILunResponse_ErrorMessage)(nil),
	}
}

type ReportIScsiSendTargetPortalsRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReportIScsiSendTargetPortalsRequest) Reset()         { *m = ReportIScsiSendTargetPortalsRequest{} }
func (m *ReportIScsiSendTargetPortalsRequest) String() string { return proto.CompactTextString(m) }
func (*ReportIScsiSendTargetPortalsRequest) ProtoMessage()    {}
func (*ReportIScsiSendTargetPortalsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_954acfae42d1ccbb, []int{2}
}

func (m *ReportIScsiSendTargetPortalsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReportIScsiSendTargetPortalsRequest.Unmarshal(m, b)
}
func (m *ReportIScsiSendTargetPortalsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReportIScsiSendTargetPortalsRequest.Marshal(b, m, deterministic)
}
func (m *ReportIScsiSendTargetPortalsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReportIScsiSendTargetPortalsRequest.Merge(m, src)
}
func (m *ReportIScsiSendTargetPortalsRequest) XXX_Size() int {
	return xxx_messageInfo_ReportIScsiSendTargetPortalsRequest.Size(m)
}
func (m *ReportIScsiSendTargetPortalsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ReportIScsiSendTargetPortalsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ReportIScsiSendTargetPortalsRequest proto.InternalMessageInfo

type IscsiPortal struct {
	// Windows name.
	SymbolicName string `protobuf:"bytes,1,opt,name=symbolic_name,json=symbolicName,proto3" json:"symbolic_name,omitempty"`
	// IP address or DNS name.
	Address string `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	// port number; should fit in a uint16.
	// If left empty, defaults to 3260
	Socket               uint32   `protobuf:"varint,3,opt,name=socket,proto3" json:"socket,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IscsiPortal) Reset()         { *m = IscsiPortal{} }
func (m *IscsiPortal) String() string { return proto.CompactTextString(m) }
func (*IscsiPortal) ProtoMessage()    {}
func (*IscsiPortal) Descriptor() ([]byte, []int) {
	return fileDescriptor_954acfae42d1ccbb, []int{3}
}

func (m *IscsiPortal) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IscsiPortal.Unmarshal(m, b)
}
func (m *IscsiPortal) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IscsiPortal.Marshal(b, m, deterministic)
}
func (m *IscsiPortal) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IscsiPortal.Merge(m, src)
}
func (m *IscsiPortal) XXX_Size() int {
	return xxx_messageInfo_IscsiPortal.Size(m)
}
func (m *IscsiPortal) XXX_DiscardUnknown() {
	xxx_messageInfo_IscsiPortal.DiscardUnknown(m)
}

var xxx_messageInfo_IscsiPortal proto.InternalMessageInfo

func (m *IscsiPortal) GetSymbolicName() string {
	if m != nil {
		return m.SymbolicName
	}
	return ""
}

func (m *IscsiPortal) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *IscsiPortal) GetSocket() uint32 {
	if m != nil {
		return m.Socket
	}
	return 0
}

// see https://docs.microsoft.com/en-us/windows/desktop/api/iscsidsc/ns-iscsidsc-iscsi_login_options
type IscsiLoginOptions struct {
	// see the "LoginFlags" section of https://docs.microsoft.com/en-us/windows/desktop/api/iscsidsc/ns-iscsidsc-iscsi_login_options
	LoginFlags           uint32          `protobuf:"varint,1,opt,name=login_flags,json=loginFlags,proto3" json:"login_flags,omitempty"`
	AuthType             IscsiAuthType   `protobuf:"varint,2,opt,name=auth_type,json=authType,proto3,enum=IscsiAuthType" json:"auth_type,omitempty"`
	HeaderDigest         IscsiDigestType `protobuf:"varint,3,opt,name=header_digest,json=headerDigest,proto3,enum=IscsiDigestType" json:"header_digest,omitempty"`
	DataDigest           IscsiDigestType `protobuf:"varint,4,opt,name=data_digest,json=dataDigest,proto3,enum=IscsiDigestType" json:"data_digest,omitempty"`
	MaximumConnections   uint32          `protobuf:"varint,5,opt,name=maximum_connections,json=maximumConnections,proto3" json:"maximum_connections,omitempty"`
	DefaultTime_2Wait    uint32          `protobuf:"varint,6,opt,name=default_time_2_wait,json=defaultTime2Wait,proto3" json:"default_time_2_wait,omitempty"`
	DefaultTime_2Retain  uint32          `protobuf:"varint,7,opt,name=default_time_2_retain,json=defaultTime2Retain,proto3" json:"default_time_2_retain,omitempty"`
	Username             string          `protobuf:"bytes,8,opt,name=username,proto3" json:"username,omitempty"`
	Password             string          `protobuf:"bytes,9,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *IscsiLoginOptions) Reset()         { *m = IscsiLoginOptions{} }
func (m *IscsiLoginOptions) String() string { return proto.CompactTextString(m) }
func (*IscsiLoginOptions) ProtoMessage()    {}
func (*IscsiLoginOptions) Descriptor() ([]byte, []int) {
	return fileDescriptor_954acfae42d1ccbb, []int{4}
}

func (m *IscsiLoginOptions) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IscsiLoginOptions.Unmarshal(m, b)
}
func (m *IscsiLoginOptions) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IscsiLoginOptions.Marshal(b, m, deterministic)
}
func (m *IscsiLoginOptions) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IscsiLoginOptions.Merge(m, src)
}
func (m *IscsiLoginOptions) XXX_Size() int {
	return xxx_messageInfo_IscsiLoginOptions.Size(m)
}
func (m *IscsiLoginOptions) XXX_DiscardUnknown() {
	xxx_messageInfo_IscsiLoginOptions.DiscardUnknown(m)
}

var xxx_messageInfo_IscsiLoginOptions proto.InternalMessageInfo

func (m *IscsiLoginOptions) GetLoginFlags() uint32 {
	if m != nil {
		return m.LoginFlags
	}
	return 0
}

func (m *IscsiLoginOptions) GetAuthType() IscsiAuthType {
	if m != nil {
		return m.AuthType
	}
	return IscsiAuthType_NoAuth
}

func (m *IscsiLoginOptions) GetHeaderDigest() IscsiDigestType {
	if m != nil {
		return m.HeaderDigest
	}
	return IscsiDigestType_NoDigest
}

func (m *IscsiLoginOptions) GetDataDigest() IscsiDigestType {
	if m != nil {
		return m.DataDigest
	}
	return IscsiDigestType_NoDigest
}

func (m *IscsiLoginOptions) GetMaximumConnections() uint32 {
	if m != nil {
		return m.MaximumConnections
	}
	return 0
}

func (m *IscsiLoginOptions) GetDefaultTime_2Wait() uint32 {
	if m != nil {
		return m.DefaultTime_2Wait
	}
	return 0
}

func (m *IscsiLoginOptions) GetDefaultTime_2Retain() uint32 {
	if m != nil {
		return m.DefaultTime_2Retain
	}
	return 0
}

func (m *IscsiLoginOptions) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *IscsiLoginOptions) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

// see https://docs.microsoft.com/en-us/windows/desktop/api/iscsidsc/ns-iscsidsc-iscsi_target_portal_info_exw
type IscsiPortalInfo struct {
	Portal              *IscsiPortal `protobuf:"bytes,1,opt,name=portal,proto3" json:"portal,omitempty"`
	InitiatorName       string       `protobuf:"bytes,2,opt,name=initiator_name,json=initiatorName,proto3" json:"initiator_name,omitempty"`
	InitiatorPortNumber uint32       `protobuf:"varint,3,opt,name=initiator_port_number,json=initiatorPortNumber,proto3" json:"initiator_port_number,omitempty"`
	// see the "SecurityFlags" section of https://docs.microsoft.com/en-us/windows/desktop/api/iscsidsc/nf-iscsidsc-addiscsisendtargetportalw
	SecurityFlags        uint64             `protobuf:"varint,4,opt,name=security_flags,json=securityFlags,proto3" json:"security_flags,omitempty"`
	LoginOptions         *IscsiLoginOptions `protobuf:"bytes,5,opt,name=login_options,json=loginOptions,proto3" json:"login_options,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *IscsiPortalInfo) Reset()         { *m = IscsiPortalInfo{} }
func (m *IscsiPortalInfo) String() string { return proto.CompactTextString(m) }
func (*IscsiPortalInfo) ProtoMessage()    {}
func (*IscsiPortalInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_954acfae42d1ccbb, []int{5}
}

func (m *IscsiPortalInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IscsiPortalInfo.Unmarshal(m, b)
}
func (m *IscsiPortalInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IscsiPortalInfo.Marshal(b, m, deterministic)
}
func (m *IscsiPortalInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IscsiPortalInfo.Merge(m, src)
}
func (m *IscsiPortalInfo) XXX_Size() int {
	return xxx_messageInfo_IscsiPortalInfo.Size(m)
}
func (m *IscsiPortalInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_IscsiPortalInfo.DiscardUnknown(m)
}

var xxx_messageInfo_IscsiPortalInfo proto.InternalMessageInfo

func (m *IscsiPortalInfo) GetPortal() *IscsiPortal {
	if m != nil {
		return m.Portal
	}
	return nil
}

func (m *IscsiPortalInfo) GetInitiatorName() string {
	if m != nil {
		return m.InitiatorName
	}
	return ""
}

func (m *IscsiPortalInfo) GetInitiatorPortNumber() uint32 {
	if m != nil {
		return m.InitiatorPortNumber
	}
	return 0
}

func (m *IscsiPortalInfo) GetSecurityFlags() uint64 {
	if m != nil {
		return m.SecurityFlags
	}
	return 0
}

func (m *IscsiPortalInfo) GetLoginOptions() *IscsiLoginOptions {
	if m != nil {
		return m.LoginOptions
	}
	return nil
}

type ReportIScsiSendTargetPortalsResponse struct {
	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	// Types that are valid to be assigned to Error:
	//	*ReportIScsiSendTargetPortalsResponse_WindowsApiError
	//	*ReportIScsiSendTargetPortalsResponse_ErrorMessage
	Error                isReportIScsiSendTargetPortalsResponse_Error `protobuf_oneof:"error"`
	PortalInfos          []*IscsiPortalInfo                           `protobuf:"bytes,4,rep,name=portal_infos,json=portalInfos,proto3" json:"portal_infos,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                                     `json:"-"`
	XXX_unrecognized     []byte                                       `json:"-"`
	XXX_sizecache        int32                                        `json:"-"`
}

func (m *ReportIScsiSendTargetPortalsResponse) Reset()         { *m = ReportIScsiSendTargetPortalsResponse{} }
func (m *ReportIScsiSendTargetPortalsResponse) String() string { return proto.CompactTextString(m) }
func (*ReportIScsiSendTargetPortalsResponse) ProtoMessage()    {}
func (*ReportIScsiSendTargetPortalsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_954acfae42d1ccbb, []int{6}
}

func (m *ReportIScsiSendTargetPortalsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReportIScsiSendTargetPortalsResponse.Unmarshal(m, b)
}
func (m *ReportIScsiSendTargetPortalsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReportIScsiSendTargetPortalsResponse.Marshal(b, m, deterministic)
}
func (m *ReportIScsiSendTargetPortalsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReportIScsiSendTargetPortalsResponse.Merge(m, src)
}
func (m *ReportIScsiSendTargetPortalsResponse) XXX_Size() int {
	return xxx_messageInfo_ReportIScsiSendTargetPortalsResponse.Size(m)
}
func (m *ReportIScsiSendTargetPortalsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ReportIScsiSendTargetPortalsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ReportIScsiSendTargetPortalsResponse proto.InternalMessageInfo

func (m *ReportIScsiSendTargetPortalsResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

type isReportIScsiSendTargetPortalsResponse_Error interface {
	isReportIScsiSendTargetPortalsResponse_Error()
}

type ReportIScsiSendTargetPortalsResponse_WindowsApiError struct {
	WindowsApiError *api.WindowsApiError `protobuf:"bytes,2,opt,name=windows_api_error,json=windowsApiError,proto3,oneof"`
}

type ReportIScsiSendTargetPortalsResponse_ErrorMessage struct {
	ErrorMessage string `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3,oneof"`
}

func (*ReportIScsiSendTargetPortalsResponse_WindowsApiError) isReportIScsiSendTargetPortalsResponse_Error() {
}

func (*ReportIScsiSendTargetPortalsResponse_ErrorMessage) isReportIScsiSendTargetPortalsResponse_Error() {
}

func (m *ReportIScsiSendTargetPortalsResponse) GetError() isReportIScsiSendTargetPortalsResponse_Error {
	if m != nil {
		return m.Error
	}
	return nil
}

func (m *ReportIScsiSendTargetPortalsResponse) GetWindowsApiError() *api.WindowsApiError {
	if x, ok := m.GetError().(*ReportIScsiSendTargetPortalsResponse_WindowsApiError); ok {
		return x.WindowsApiError
	}
	return nil
}

func (m *ReportIScsiSendTargetPortalsResponse) GetErrorMessage() string {
	if x, ok := m.GetError().(*ReportIScsiSendTargetPortalsResponse_ErrorMessage); ok {
		return x.ErrorMessage
	}
	return ""
}

func (m *ReportIScsiSendTargetPortalsResponse) GetPortalInfos() []*IscsiPortalInfo {
	if m != nil {
		return m.PortalInfos
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*ReportIScsiSendTargetPortalsResponse) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*ReportIScsiSendTargetPortalsResponse_WindowsApiError)(nil),
		(*ReportIScsiSendTargetPortalsResponse_ErrorMessage)(nil),
	}
}

type AddIScsiSendTargetPortalRequest struct {
	InitiatorInstance    string             `protobuf:"bytes,1,opt,name=initiator_instance,json=initiatorInstance,proto3" json:"initiator_instance,omitempty"`
	InitiatorPortNumber  uint32             `protobuf:"varint,2,opt,name=initiator_port_number,json=initiatorPortNumber,proto3" json:"initiator_port_number,omitempty"`
	LoginOptions         *IscsiLoginOptions `protobuf:"bytes,3,opt,name=login_options,json=loginOptions,proto3" json:"login_options,omitempty"`
	SecurityFlags        uint64             `protobuf:"varint,4,opt,name=security_flags,json=securityFlags,proto3" json:"security_flags,omitempty"`
	Portal               *IscsiPortal       `protobuf:"bytes,5,opt,name=portal,proto3" json:"portal,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *AddIScsiSendTargetPortalRequest) Reset()         { *m = AddIScsiSendTargetPortalRequest{} }
func (m *AddIScsiSendTargetPortalRequest) String() string { return proto.CompactTextString(m) }
func (*AddIScsiSendTargetPortalRequest) ProtoMessage()    {}
func (*AddIScsiSendTargetPortalRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_954acfae42d1ccbb, []int{7}
}

func (m *AddIScsiSendTargetPortalRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddIScsiSendTargetPortalRequest.Unmarshal(m, b)
}
func (m *AddIScsiSendTargetPortalRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddIScsiSendTargetPortalRequest.Marshal(b, m, deterministic)
}
func (m *AddIScsiSendTargetPortalRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddIScsiSendTargetPortalRequest.Merge(m, src)
}
func (m *AddIScsiSendTargetPortalRequest) XXX_Size() int {
	return xxx_messageInfo_AddIScsiSendTargetPortalRequest.Size(m)
}
func (m *AddIScsiSendTargetPortalRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddIScsiSendTargetPortalRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddIScsiSendTargetPortalRequest proto.InternalMessageInfo

func (m *AddIScsiSendTargetPortalRequest) GetInitiatorInstance() string {
	if m != nil {
		return m.InitiatorInstance
	}
	return ""
}

func (m *AddIScsiSendTargetPortalRequest) GetInitiatorPortNumber() uint32 {
	if m != nil {
		return m.InitiatorPortNumber
	}
	return 0
}

func (m *AddIScsiSendTargetPortalRequest) GetLoginOptions() *IscsiLoginOptions {
	if m != nil {
		return m.LoginOptions
	}
	return nil
}

func (m *AddIScsiSendTargetPortalRequest) GetSecurityFlags() uint64 {
	if m != nil {
		return m.SecurityFlags
	}
	return 0
}

func (m *AddIScsiSendTargetPortalRequest) GetPortal() *IscsiPortal {
	if m != nil {
		return m.Portal
	}
	return nil
}

type AddIScsiSendTargetPortalResponse struct {
	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	// Types that are valid to be assigned to Error:
	//	*AddIScsiSendTargetPortalResponse_WindowsApiError
	//	*AddIScsiSendTargetPortalResponse_ErrorMessage
	Error                isAddIScsiSendTargetPortalResponse_Error `protobuf_oneof:"error"`
	XXX_NoUnkeyedLiteral struct{}                                 `json:"-"`
	XXX_unrecognized     []byte                                   `json:"-"`
	XXX_sizecache        int32                                    `json:"-"`
}

func (m *AddIScsiSendTargetPortalResponse) Reset()         { *m = AddIScsiSendTargetPortalResponse{} }
func (m *AddIScsiSendTargetPortalResponse) String() string { return proto.CompactTextString(m) }
func (*AddIScsiSendTargetPortalResponse) ProtoMessage()    {}
func (*AddIScsiSendTargetPortalResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_954acfae42d1ccbb, []int{8}
}

func (m *AddIScsiSendTargetPortalResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddIScsiSendTargetPortalResponse.Unmarshal(m, b)
}
func (m *AddIScsiSendTargetPortalResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddIScsiSendTargetPortalResponse.Marshal(b, m, deterministic)
}
func (m *AddIScsiSendTargetPortalResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddIScsiSendTargetPortalResponse.Merge(m, src)
}
func (m *AddIScsiSendTargetPortalResponse) XXX_Size() int {
	return xxx_messageInfo_AddIScsiSendTargetPortalResponse.Size(m)
}
func (m *AddIScsiSendTargetPortalResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AddIScsiSendTargetPortalResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AddIScsiSendTargetPortalResponse proto.InternalMessageInfo

func (m *AddIScsiSendTargetPortalResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

type isAddIScsiSendTargetPortalResponse_Error interface {
	isAddIScsiSendTargetPortalResponse_Error()
}

type AddIScsiSendTargetPortalResponse_WindowsApiError struct {
	WindowsApiError *api.WindowsApiError `protobuf:"bytes,2,opt,name=windows_api_error,json=windowsApiError,proto3,oneof"`
}

type AddIScsiSendTargetPortalResponse_ErrorMessage struct {
	ErrorMessage string `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3,oneof"`
}

func (*AddIScsiSendTargetPortalResponse_WindowsApiError) isAddIScsiSendTargetPortalResponse_Error() {}

func (*AddIScsiSendTargetPortalResponse_ErrorMessage) isAddIScsiSendTargetPortalResponse_Error() {}

func (m *AddIScsiSendTargetPortalResponse) GetError() isAddIScsiSendTargetPortalResponse_Error {
	if m != nil {
		return m.Error
	}
	return nil
}

func (m *AddIScsiSendTargetPortalResponse) GetWindowsApiError() *api.WindowsApiError {
	if x, ok := m.GetError().(*AddIScsiSendTargetPortalResponse_WindowsApiError); ok {
		return x.WindowsApiError
	}
	return nil
}

func (m *AddIScsiSendTargetPortalResponse) GetErrorMessage() string {
	if x, ok := m.GetError().(*AddIScsiSendTargetPortalResponse_ErrorMessage); ok {
		return x.ErrorMessage
	}
	return ""
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*AddIScsiSendTargetPortalResponse) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*AddIScsiSendTargetPortalResponse_WindowsApiError)(nil),
		(*AddIScsiSendTargetPortalResponse_ErrorMessage)(nil),
	}
}

type RemoveIScsiSendTargetPortalRequest struct {
	InitiatorInstance    string       `protobuf:"bytes,1,opt,name=initiator_instance,json=initiatorInstance,proto3" json:"initiator_instance,omitempty"`
	InitiatorPortNumber  uint32       `protobuf:"varint,2,opt,name=initiator_port_number,json=initiatorPortNumber,proto3" json:"initiator_port_number,omitempty"`
	Portal               *IscsiPortal `protobuf:"bytes,3,opt,name=portal,proto3" json:"portal,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *RemoveIScsiSendTargetPortalRequest) Reset()         { *m = RemoveIScsiSendTargetPortalRequest{} }
func (m *RemoveIScsiSendTargetPortalRequest) String() string { return proto.CompactTextString(m) }
func (*RemoveIScsiSendTargetPortalRequest) ProtoMessage()    {}
func (*RemoveIScsiSendTargetPortalRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_954acfae42d1ccbb, []int{9}
}

func (m *RemoveIScsiSendTargetPortalRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemoveIScsiSendTargetPortalRequest.Unmarshal(m, b)
}
func (m *RemoveIScsiSendTargetPortalRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemoveIScsiSendTargetPortalRequest.Marshal(b, m, deterministic)
}
func (m *RemoveIScsiSendTargetPortalRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoveIScsiSendTargetPortalRequest.Merge(m, src)
}
func (m *RemoveIScsiSendTargetPortalRequest) XXX_Size() int {
	return xxx_messageInfo_RemoveIScsiSendTargetPortalRequest.Size(m)
}
func (m *RemoveIScsiSendTargetPortalRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoveIScsiSendTargetPortalRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RemoveIScsiSendTargetPortalRequest proto.InternalMessageInfo

func (m *RemoveIScsiSendTargetPortalRequest) GetInitiatorInstance() string {
	if m != nil {
		return m.InitiatorInstance
	}
	return ""
}

func (m *RemoveIScsiSendTargetPortalRequest) GetInitiatorPortNumber() uint32 {
	if m != nil {
		return m.InitiatorPortNumber
	}
	return 0
}

func (m *RemoveIScsiSendTargetPortalRequest) GetPortal() *IscsiPortal {
	if m != nil {
		return m.Portal
	}
	return nil
}

type RemoveIScsiSendTargetPortalResponse struct {
	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	// Types that are valid to be assigned to Error:
	//	*RemoveIScsiSendTargetPortalResponse_WindowsApiError
	//	*RemoveIScsiSendTargetPortalResponse_ErrorMessage
	Error                isRemoveIScsiSendTargetPortalResponse_Error `protobuf_oneof:"error"`
	XXX_NoUnkeyedLiteral struct{}                                    `json:"-"`
	XXX_unrecognized     []byte                                      `json:"-"`
	XXX_sizecache        int32                                       `json:"-"`
}

func (m *RemoveIScsiSendTargetPortalResponse) Reset()         { *m = RemoveIScsiSendTargetPortalResponse{} }
func (m *RemoveIScsiSendTargetPortalResponse) String() string { return proto.CompactTextString(m) }
func (*RemoveIScsiSendTargetPortalResponse) ProtoMessage()    {}
func (*RemoveIScsiSendTargetPortalResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_954acfae42d1ccbb, []int{10}
}

func (m *RemoveIScsiSendTargetPortalResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemoveIScsiSendTargetPortalResponse.Unmarshal(m, b)
}
func (m *RemoveIScsiSendTargetPortalResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemoveIScsiSendTargetPortalResponse.Marshal(b, m, deterministic)
}
func (m *RemoveIScsiSendTargetPortalResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoveIScsiSendTargetPortalResponse.Merge(m, src)
}
func (m *RemoveIScsiSendTargetPortalResponse) XXX_Size() int {
	return xxx_messageInfo_RemoveIScsiSendTargetPortalResponse.Size(m)
}
func (m *RemoveIScsiSendTargetPortalResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoveIScsiSendTargetPortalResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RemoveIScsiSendTargetPortalResponse proto.InternalMessageInfo

func (m *RemoveIScsiSendTargetPortalResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

type isRemoveIScsiSendTargetPortalResponse_Error interface {
	isRemoveIScsiSendTargetPortalResponse_Error()
}

type RemoveIScsiSendTargetPortalResponse_WindowsApiError struct {
	WindowsApiError *api.WindowsApiError `protobuf:"bytes,2,opt,name=windows_api_error,json=windowsApiError,proto3,oneof"`
}

type RemoveIScsiSendTargetPortalResponse_ErrorMessage struct {
	ErrorMessage string `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3,oneof"`
}

func (*RemoveIScsiSendTargetPortalResponse_WindowsApiError) isRemoveIScsiSendTargetPortalResponse_Error() {
}

func (*RemoveIScsiSendTargetPortalResponse_ErrorMessage) isRemoveIScsiSendTargetPortalResponse_Error() {
}

func (m *RemoveIScsiSendTargetPortalResponse) GetError() isRemoveIScsiSendTargetPortalResponse_Error {
	if m != nil {
		return m.Error
	}
	return nil
}

func (m *RemoveIScsiSendTargetPortalResponse) GetWindowsApiError() *api.WindowsApiError {
	if x, ok := m.GetError().(*RemoveIScsiSendTargetPortalResponse_WindowsApiError); ok {
		return x.WindowsApiError
	}
	return nil
}

func (m *RemoveIScsiSendTargetPortalResponse) GetErrorMessage() string {
	if x, ok := m.GetError().(*RemoveIScsiSendTargetPortalResponse_ErrorMessage); ok {
		return x.ErrorMessage
	}
	return ""
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*RemoveIScsiSendTargetPortalResponse) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*RemoveIScsiSendTargetPortalResponse_WindowsApiError)(nil),
		(*RemoveIScsiSendTargetPortalResponse_ErrorMessage)(nil),
	}
}

type ReportIScsiTargetsRequest struct {
	// if true,  the iSCSI initiator service updates the list of discovered targets before
	// returning the target list data to the caller.
	ForceUpdate          bool     `protobuf:"varint,1,opt,name=force_update,json=forceUpdate,proto3" json:"force_update,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReportIScsiTargetsRequest) Reset()         { *m = ReportIScsiTargetsRequest{} }
func (m *ReportIScsiTargetsRequest) String() string { return proto.CompactTextString(m) }
func (*ReportIScsiTargetsRequest) ProtoMessage()    {}
func (*ReportIScsiTargetsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_954acfae42d1ccbb, []int{11}
}

func (m *ReportIScsiTargetsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReportIScsiTargetsRequest.Unmarshal(m, b)
}
func (m *ReportIScsiTargetsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReportIScsiTargetsRequest.Marshal(b, m, deterministic)
}
func (m *ReportIScsiTargetsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReportIScsiTargetsRequest.Merge(m, src)
}
func (m *ReportIScsiTargetsRequest) XXX_Size() int {
	return xxx_messageInfo_ReportIScsiTargetsRequest.Size(m)
}
func (m *ReportIScsiTargetsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ReportIScsiTargetsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ReportIScsiTargetsRequest proto.InternalMessageInfo

func (m *ReportIScsiTargetsRequest) GetForceUpdate() bool {
	if m != nil {
		return m.ForceUpdate
	}
	return false
}

type ReportIScsiTargetsResponse struct {
	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	// Types that are valid to be assigned to Error:
	//	*ReportIScsiTargetsResponse_WindowsApiError
	//	*ReportIScsiTargetsResponse_ErrorMessage
	Error                isReportIScsiTargetsResponse_Error `protobuf_oneof:"error"`
	TargetNames          []string                           `protobuf:"bytes,4,rep,name=target_names,json=targetNames,proto3" json:"target_names,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                           `json:"-"`
	XXX_unrecognized     []byte                             `json:"-"`
	XXX_sizecache        int32                              `json:"-"`
}

func (m *ReportIScsiTargetsResponse) Reset()         { *m = ReportIScsiTargetsResponse{} }
func (m *ReportIScsiTargetsResponse) String() string { return proto.CompactTextString(m) }
func (*ReportIScsiTargetsResponse) ProtoMessage()    {}
func (*ReportIScsiTargetsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_954acfae42d1ccbb, []int{12}
}

func (m *ReportIScsiTargetsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReportIScsiTargetsResponse.Unmarshal(m, b)
}
func (m *ReportIScsiTargetsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReportIScsiTargetsResponse.Marshal(b, m, deterministic)
}
func (m *ReportIScsiTargetsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReportIScsiTargetsResponse.Merge(m, src)
}
func (m *ReportIScsiTargetsResponse) XXX_Size() int {
	return xxx_messageInfo_ReportIScsiTargetsResponse.Size(m)
}
func (m *ReportIScsiTargetsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ReportIScsiTargetsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ReportIScsiTargetsResponse proto.InternalMessageInfo

func (m *ReportIScsiTargetsResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

type isReportIScsiTargetsResponse_Error interface {
	isReportIScsiTargetsResponse_Error()
}

type ReportIScsiTargetsResponse_WindowsApiError struct {
	WindowsApiError *api.WindowsApiError `protobuf:"bytes,2,opt,name=windows_api_error,json=windowsApiError,proto3,oneof"`
}

type ReportIScsiTargetsResponse_ErrorMessage struct {
	ErrorMessage string `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3,oneof"`
}

func (*ReportIScsiTargetsResponse_WindowsApiError) isReportIScsiTargetsResponse_Error() {}

func (*ReportIScsiTargetsResponse_ErrorMessage) isReportIScsiTargetsResponse_Error() {}

func (m *ReportIScsiTargetsResponse) GetError() isReportIScsiTargetsResponse_Error {
	if m != nil {
		return m.Error
	}
	return nil
}

func (m *ReportIScsiTargetsResponse) GetWindowsApiError() *api.WindowsApiError {
	if x, ok := m.GetError().(*ReportIScsiTargetsResponse_WindowsApiError); ok {
		return x.WindowsApiError
	}
	return nil
}

func (m *ReportIScsiTargetsResponse) GetErrorMessage() string {
	if x, ok := m.GetError().(*ReportIScsiTargetsResponse_ErrorMessage); ok {
		return x.ErrorMessage
	}
	return ""
}

func (m *ReportIScsiTargetsResponse) GetTargetNames() []string {
	if m != nil {
		return m.TargetNames
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*ReportIScsiTargetsResponse) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*ReportIScsiTargetsResponse_WindowsApiError)(nil),
		(*ReportIScsiTargetsResponse_ErrorMessage)(nil),
	}
}

type LoginIscsiTargetRequest struct {
	TargetName             string             `protobuf:"bytes,1,opt,name=target_name,json=targetName,proto3" json:"target_name,omitempty"`
	IsInformationalSession bool               `protobuf:"varint,2,opt,name=is_informational_session,json=isInformationalSession,proto3" json:"is_informational_session,omitempty"`
	InitiatorInstance      string             `protobuf:"bytes,3,opt,name=initiator_instance,json=initiatorInstance,proto3" json:"initiator_instance,omitempty"`
	InitiatorPortNumber    uint32             `protobuf:"varint,4,opt,name=initiator_port_number,json=initiatorPortNumber,proto3" json:"initiator_port_number,omitempty"`
	TargetPortal           *IscsiPortal       `protobuf:"bytes,5,opt,name=target_portal,json=targetPortal,proto3" json:"target_portal,omitempty"`
	SecurityFlags          uint64             `protobuf:"varint,6,opt,name=security_flags,json=securityFlags,proto3" json:"security_flags,omitempty"`
	LoginOptions           *IscsiLoginOptions `protobuf:"bytes,7,opt,name=login_options,json=loginOptions,proto3" json:"login_options,omitempty"`
	Key                    string             `protobuf:"bytes,8,opt,name=key,proto3" json:"key,omitempty"`
	IsPersistent           bool               `protobuf:"varint,9,opt,name=is_persistent,json=isPersistent,proto3" json:"is_persistent,omitempty"`
	XXX_NoUnkeyedLiteral   struct{}           `json:"-"`
	XXX_unrecognized       []byte             `json:"-"`
	XXX_sizecache          int32              `json:"-"`
}

func (m *LoginIscsiTargetRequest) Reset()         { *m = LoginIscsiTargetRequest{} }
func (m *LoginIscsiTargetRequest) String() string { return proto.CompactTextString(m) }
func (*LoginIscsiTargetRequest) ProtoMessage()    {}
func (*LoginIscsiTargetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_954acfae42d1ccbb, []int{13}
}

func (m *LoginIscsiTargetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginIscsiTargetRequest.Unmarshal(m, b)
}
func (m *LoginIscsiTargetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginIscsiTargetRequest.Marshal(b, m, deterministic)
}
func (m *LoginIscsiTargetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginIscsiTargetRequest.Merge(m, src)
}
func (m *LoginIscsiTargetRequest) XXX_Size() int {
	return xxx_messageInfo_LoginIscsiTargetRequest.Size(m)
}
func (m *LoginIscsiTargetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginIscsiTargetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LoginIscsiTargetRequest proto.InternalMessageInfo

func (m *LoginIscsiTargetRequest) GetTargetName() string {
	if m != nil {
		return m.TargetName
	}
	return ""
}

func (m *LoginIscsiTargetRequest) GetIsInformationalSession() bool {
	if m != nil {
		return m.IsInformationalSession
	}
	return false
}

func (m *LoginIscsiTargetRequest) GetInitiatorInstance() string {
	if m != nil {
		return m.InitiatorInstance
	}
	return ""
}

func (m *LoginIscsiTargetRequest) GetInitiatorPortNumber() uint32 {
	if m != nil {
		return m.InitiatorPortNumber
	}
	return 0
}

func (m *LoginIscsiTargetRequest) GetTargetPortal() *IscsiPortal {
	if m != nil {
		return m.TargetPortal
	}
	return nil
}

func (m *LoginIscsiTargetRequest) GetSecurityFlags() uint64 {
	if m != nil {
		return m.SecurityFlags
	}
	return 0
}

func (m *LoginIscsiTargetRequest) GetLoginOptions() *IscsiLoginOptions {
	if m != nil {
		return m.LoginOptions
	}
	return nil
}

func (m *LoginIscsiTargetRequest) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *LoginIscsiTargetRequest) GetIsPersistent() bool {
	if m != nil {
		return m.IsPersistent
	}
	return false
}

type IscsiID struct {
	AdapterUnique        uint64   `protobuf:"varint,1,opt,name=adapter_unique,json=adapterUnique,proto3" json:"adapter_unique,omitempty"`
	AdapterSpecific      uint64   `protobuf:"varint,2,opt,name=adapter_specific,json=adapterSpecific,proto3" json:"adapter_specific,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IscsiID) Reset()         { *m = IscsiID{} }
func (m *IscsiID) String() string { return proto.CompactTextString(m) }
func (*IscsiID) ProtoMessage()    {}
func (*IscsiID) Descriptor() ([]byte, []int) {
	return fileDescriptor_954acfae42d1ccbb, []int{14}
}

func (m *IscsiID) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IscsiID.Unmarshal(m, b)
}
func (m *IscsiID) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IscsiID.Marshal(b, m, deterministic)
}
func (m *IscsiID) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IscsiID.Merge(m, src)
}
func (m *IscsiID) XXX_Size() int {
	return xxx_messageInfo_IscsiID.Size(m)
}
func (m *IscsiID) XXX_DiscardUnknown() {
	xxx_messageInfo_IscsiID.DiscardUnknown(m)
}

var xxx_messageInfo_IscsiID proto.InternalMessageInfo

func (m *IscsiID) GetAdapterUnique() uint64 {
	if m != nil {
		return m.AdapterUnique
	}
	return 0
}

func (m *IscsiID) GetAdapterSpecific() uint64 {
	if m != nil {
		return m.AdapterSpecific
	}
	return 0
}

type LoginIscsiTargetResponse struct {
	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	// Types that are valid to be assigned to Error:
	//	*LoginIscsiTargetResponse_WindowsApiError
	//	*LoginIscsiTargetResponse_ErrorMessage
	Error                isLoginIscsiTargetResponse_Error `protobuf_oneof:"error"`
	SessionId            *IscsiID                         `protobuf:"bytes,4,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	ConnectionId         *IscsiID                         `protobuf:"bytes,5,opt,name=connection_id,json=connectionId,proto3" json:"connection_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                         `json:"-"`
	XXX_unrecognized     []byte                           `json:"-"`
	XXX_sizecache        int32                            `json:"-"`
}

func (m *LoginIscsiTargetResponse) Reset()         { *m = LoginIscsiTargetResponse{} }
func (m *LoginIscsiTargetResponse) String() string { return proto.CompactTextString(m) }
func (*LoginIscsiTargetResponse) ProtoMessage()    {}
func (*LoginIscsiTargetResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_954acfae42d1ccbb, []int{15}
}

func (m *LoginIscsiTargetResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginIscsiTargetResponse.Unmarshal(m, b)
}
func (m *LoginIscsiTargetResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginIscsiTargetResponse.Marshal(b, m, deterministic)
}
func (m *LoginIscsiTargetResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginIscsiTargetResponse.Merge(m, src)
}
func (m *LoginIscsiTargetResponse) XXX_Size() int {
	return xxx_messageInfo_LoginIscsiTargetResponse.Size(m)
}
func (m *LoginIscsiTargetResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginIscsiTargetResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LoginIscsiTargetResponse proto.InternalMessageInfo

func (m *LoginIscsiTargetResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

type isLoginIscsiTargetResponse_Error interface {
	isLoginIscsiTargetResponse_Error()
}

type LoginIscsiTargetResponse_WindowsApiError struct {
	WindowsApiError *api.WindowsApiError `protobuf:"bytes,2,opt,name=windows_api_error,json=windowsApiError,proto3,oneof"`
}

type LoginIscsiTargetResponse_ErrorMessage struct {
	ErrorMessage string `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3,oneof"`
}

func (*LoginIscsiTargetResponse_WindowsApiError) isLoginIscsiTargetResponse_Error() {}

func (*LoginIscsiTargetResponse_ErrorMessage) isLoginIscsiTargetResponse_Error() {}

func (m *LoginIscsiTargetResponse) GetError() isLoginIscsiTargetResponse_Error {
	if m != nil {
		return m.Error
	}
	return nil
}

func (m *LoginIscsiTargetResponse) GetWindowsApiError() *api.WindowsApiError {
	if x, ok := m.GetError().(*LoginIscsiTargetResponse_WindowsApiError); ok {
		return x.WindowsApiError
	}
	return nil
}

func (m *LoginIscsiTargetResponse) GetErrorMessage() string {
	if x, ok := m.GetError().(*LoginIscsiTargetResponse_ErrorMessage); ok {
		return x.ErrorMessage
	}
	return ""
}

func (m *LoginIscsiTargetResponse) GetSessionId() *IscsiID {
	if m != nil {
		return m.SessionId
	}
	return nil
}

func (m *LoginIscsiTargetResponse) GetConnectionId() *IscsiID {
	if m != nil {
		return m.ConnectionId
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*LoginIscsiTargetResponse) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*LoginIscsiTargetResponse_WindowsApiError)(nil),
		(*LoginIscsiTargetResponse_ErrorMessage)(nil),
	}
}

type LogoutIScsiTargetRequest struct {
	SessionId            *IscsiID `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LogoutIScsiTargetRequest) Reset()         { *m = LogoutIScsiTargetRequest{} }
func (m *LogoutIScsiTargetRequest) String() string { return proto.CompactTextString(m) }
func (*LogoutIScsiTargetRequest) ProtoMessage()    {}
func (*LogoutIScsiTargetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_954acfae42d1ccbb, []int{16}
}

func (m *LogoutIScsiTargetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LogoutIScsiTargetRequest.Unmarshal(m, b)
}
func (m *LogoutIScsiTargetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LogoutIScsiTargetRequest.Marshal(b, m, deterministic)
}
func (m *LogoutIScsiTargetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LogoutIScsiTargetRequest.Merge(m, src)
}
func (m *LogoutIScsiTargetRequest) XXX_Size() int {
	return xxx_messageInfo_LogoutIScsiTargetRequest.Size(m)
}
func (m *LogoutIScsiTargetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LogoutIScsiTargetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LogoutIScsiTargetRequest proto.InternalMessageInfo

func (m *LogoutIScsiTargetRequest) GetSessionId() *IscsiID {
	if m != nil {
		return m.SessionId
	}
	return nil
}

type LogoutIScsiTargetResponse struct {
	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	// Types that are valid to be assigned to Error:
	//	*LogoutIScsiTargetResponse_WindowsApiError
	//	*LogoutIScsiTargetResponse_ErrorMessage
	Error                isLogoutIScsiTargetResponse_Error `protobuf_oneof:"error"`
	XXX_NoUnkeyedLiteral struct{}                          `json:"-"`
	XXX_unrecognized     []byte                            `json:"-"`
	XXX_sizecache        int32                             `json:"-"`
}

func (m *LogoutIScsiTargetResponse) Reset()         { *m = LogoutIScsiTargetResponse{} }
func (m *LogoutIScsiTargetResponse) String() string { return proto.CompactTextString(m) }
func (*LogoutIScsiTargetResponse) ProtoMessage()    {}
func (*LogoutIScsiTargetResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_954acfae42d1ccbb, []int{17}
}

func (m *LogoutIScsiTargetResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LogoutIScsiTargetResponse.Unmarshal(m, b)
}
func (m *LogoutIScsiTargetResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LogoutIScsiTargetResponse.Marshal(b, m, deterministic)
}
func (m *LogoutIScsiTargetResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LogoutIScsiTargetResponse.Merge(m, src)
}
func (m *LogoutIScsiTargetResponse) XXX_Size() int {
	return xxx_messageInfo_LogoutIScsiTargetResponse.Size(m)
}
func (m *LogoutIScsiTargetResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LogoutIScsiTargetResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LogoutIScsiTargetResponse proto.InternalMessageInfo

func (m *LogoutIScsiTargetResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

type isLogoutIScsiTargetResponse_Error interface {
	isLogoutIScsiTargetResponse_Error()
}

type LogoutIScsiTargetResponse_WindowsApiError struct {
	WindowsApiError *api.WindowsApiError `protobuf:"bytes,2,opt,name=windows_api_error,json=windowsApiError,proto3,oneof"`
}

type LogoutIScsiTargetResponse_ErrorMessage struct {
	ErrorMessage string `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3,oneof"`
}

func (*LogoutIScsiTargetResponse_WindowsApiError) isLogoutIScsiTargetResponse_Error() {}

func (*LogoutIScsiTargetResponse_ErrorMessage) isLogoutIScsiTargetResponse_Error() {}

func (m *LogoutIScsiTargetResponse) GetError() isLogoutIScsiTargetResponse_Error {
	if m != nil {
		return m.Error
	}
	return nil
}

func (m *LogoutIScsiTargetResponse) GetWindowsApiError() *api.WindowsApiError {
	if x, ok := m.GetError().(*LogoutIScsiTargetResponse_WindowsApiError); ok {
		return x.WindowsApiError
	}
	return nil
}

func (m *LogoutIScsiTargetResponse) GetErrorMessage() string {
	if x, ok := m.GetError().(*LogoutIScsiTargetResponse_ErrorMessage); ok {
		return x.ErrorMessage
	}
	return ""
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*LogoutIScsiTargetResponse) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*LogoutIScsiTargetResponse_WindowsApiError)(nil),
		(*LogoutIScsiTargetResponse_ErrorMessage)(nil),
	}
}

type GetIScsiSessionListRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetIScsiSessionListRequest) Reset()         { *m = GetIScsiSessionListRequest{} }
func (m *GetIScsiSessionListRequest) String() string { return proto.CompactTextString(m) }
func (*GetIScsiSessionListRequest) ProtoMessage()    {}
func (*GetIScsiSessionListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_954acfae42d1ccbb, []int{18}
}

func (m *GetIScsiSessionListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetIScsiSessionListRequest.Unmarshal(m, b)
}
func (m *GetIScsiSessionListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetIScsiSessionListRequest.Marshal(b, m, deterministic)
}
func (m *GetIScsiSessionListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetIScsiSessionListRequest.Merge(m, src)
}
func (m *GetIScsiSessionListRequest) XXX_Size() int {
	return xxx_messageInfo_GetIScsiSessionListRequest.Size(m)
}
func (m *GetIScsiSessionListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetIScsiSessionListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetIScsiSessionListRequest proto.InternalMessageInfo

type IscsiConnectionInfo struct {
	ConnectionId         *IscsiID `protobuf:"bytes,1,opt,name=connection_id,json=connectionId,proto3" json:"connection_id,omitempty"`
	InitiatorAddress     string   `protobuf:"bytes,2,opt,name=initiator_address,json=initiatorAddress,proto3" json:"initiator_address,omitempty"`
	TargetAddress        string   `protobuf:"bytes,3,opt,name=target_address,json=targetAddress,proto3" json:"target_address,omitempty"`
	InitiatorSocket      uint32   `protobuf:"varint,4,opt,name=initiator_socket,json=initiatorSocket,proto3" json:"initiator_socket,omitempty"`
	TargetSocket         uint32   `protobuf:"varint,5,opt,name=target_socket,json=targetSocket,proto3" json:"target_socket,omitempty"`
	CID                  []byte   `protobuf:"bytes,6,opt,name=CID,proto3" json:"CID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IscsiConnectionInfo) Reset()         { *m = IscsiConnectionInfo{} }
func (m *IscsiConnectionInfo) String() string { return proto.CompactTextString(m) }
func (*IscsiConnectionInfo) ProtoMessage()    {}
func (*IscsiConnectionInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_954acfae42d1ccbb, []int{19}
}

func (m *IscsiConnectionInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IscsiConnectionInfo.Unmarshal(m, b)
}
func (m *IscsiConnectionInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IscsiConnectionInfo.Marshal(b, m, deterministic)
}
func (m *IscsiConnectionInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IscsiConnectionInfo.Merge(m, src)
}
func (m *IscsiConnectionInfo) XXX_Size() int {
	return xxx_messageInfo_IscsiConnectionInfo.Size(m)
}
func (m *IscsiConnectionInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_IscsiConnectionInfo.DiscardUnknown(m)
}

var xxx_messageInfo_IscsiConnectionInfo proto.InternalMessageInfo

func (m *IscsiConnectionInfo) GetConnectionId() *IscsiID {
	if m != nil {
		return m.ConnectionId
	}
	return nil
}

func (m *IscsiConnectionInfo) GetInitiatorAddress() string {
	if m != nil {
		return m.InitiatorAddress
	}
	return ""
}

func (m *IscsiConnectionInfo) GetTargetAddress() string {
	if m != nil {
		return m.TargetAddress
	}
	return ""
}

func (m *IscsiConnectionInfo) GetInitiatorSocket() uint32 {
	if m != nil {
		return m.InitiatorSocket
	}
	return 0
}

func (m *IscsiConnectionInfo) GetTargetSocket() uint32 {
	if m != nil {
		return m.TargetSocket
	}
	return 0
}

func (m *IscsiConnectionInfo) GetCID() []byte {
	if m != nil {
		return m.CID
	}
	return nil
}

// see https://docs.microsoft.com/en-us/windows/desktop/api/iscsidsc/ns-iscsidsc-iscsi_session_infow
type IscsiSessionInfo struct {
	SessionId            *IscsiID               `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	InitiatorName        string                 `protobuf:"bytes,2,opt,name=initiator_name,json=initiatorName,proto3" json:"initiator_name,omitempty"`
	TargetNodeName       string                 `protobuf:"bytes,3,opt,name=target_node_name,json=targetNodeName,proto3" json:"target_node_name,omitempty"`
	TargetName           string                 `protobuf:"bytes,4,opt,name=target_name,json=targetName,proto3" json:"target_name,omitempty"`
	ISID                 []byte                 `protobuf:"bytes,5,opt,name=ISID,proto3" json:"ISID,omitempty"`
	TSID                 []byte                 `protobuf:"bytes,6,opt,name=TSID,proto3" json:"TSID,omitempty"`
	Connections          []*IscsiConnectionInfo `protobuf:"bytes,7,rep,name=connections,proto3" json:"connections,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *IscsiSessionInfo) Reset()         { *m = IscsiSessionInfo{} }
func (m *IscsiSessionInfo) String() string { return proto.CompactTextString(m) }
func (*IscsiSessionInfo) ProtoMessage()    {}
func (*IscsiSessionInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_954acfae42d1ccbb, []int{20}
}

func (m *IscsiSessionInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IscsiSessionInfo.Unmarshal(m, b)
}
func (m *IscsiSessionInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IscsiSessionInfo.Marshal(b, m, deterministic)
}
func (m *IscsiSessionInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IscsiSessionInfo.Merge(m, src)
}
func (m *IscsiSessionInfo) XXX_Size() int {
	return xxx_messageInfo_IscsiSessionInfo.Size(m)
}
func (m *IscsiSessionInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_IscsiSessionInfo.DiscardUnknown(m)
}

var xxx_messageInfo_IscsiSessionInfo proto.InternalMessageInfo

func (m *IscsiSessionInfo) GetSessionId() *IscsiID {
	if m != nil {
		return m.SessionId
	}
	return nil
}

func (m *IscsiSessionInfo) GetInitiatorName() string {
	if m != nil {
		return m.InitiatorName
	}
	return ""
}

func (m *IscsiSessionInfo) GetTargetNodeName() string {
	if m != nil {
		return m.TargetNodeName
	}
	return ""
}

func (m *IscsiSessionInfo) GetTargetName() string {
	if m != nil {
		return m.TargetName
	}
	return ""
}

func (m *IscsiSessionInfo) GetISID() []byte {
	if m != nil {
		return m.ISID
	}
	return nil
}

func (m *IscsiSessionInfo) GetTSID() []byte {
	if m != nil {
		return m.TSID
	}
	return nil
}

func (m *IscsiSessionInfo) GetConnections() []*IscsiConnectionInfo {
	if m != nil {
		return m.Connections
	}
	return nil
}

type GetIScsiSessionListResponse struct {
	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	// Types that are valid to be assigned to Error:
	//	*GetIScsiSessionListResponse_WindowsApiError
	//	*GetIScsiSessionListResponse_ErrorMessage
	Error                isGetIScsiSessionListResponse_Error `protobuf_oneof:"error"`
	SessionInfos         []*IscsiSessionInfo                 `protobuf:"bytes,4,rep,name=session_infos,json=sessionInfos,proto3" json:"session_infos,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                            `json:"-"`
	XXX_unrecognized     []byte                              `json:"-"`
	XXX_sizecache        int32                               `json:"-"`
}

func (m *GetIScsiSessionListResponse) Reset()         { *m = GetIScsiSessionListResponse{} }
func (m *GetIScsiSessionListResponse) String() string { return proto.CompactTextString(m) }
func (*GetIScsiSessionListResponse) ProtoMessage()    {}
func (*GetIScsiSessionListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_954acfae42d1ccbb, []int{21}
}

func (m *GetIScsiSessionListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetIScsiSessionListResponse.Unmarshal(m, b)
}
func (m *GetIScsiSessionListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetIScsiSessionListResponse.Marshal(b, m, deterministic)
}
func (m *GetIScsiSessionListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetIScsiSessionListResponse.Merge(m, src)
}
func (m *GetIScsiSessionListResponse) XXX_Size() int {
	return xxx_messageInfo_GetIScsiSessionListResponse.Size(m)
}
func (m *GetIScsiSessionListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetIScsiSessionListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetIScsiSessionListResponse proto.InternalMessageInfo

func (m *GetIScsiSessionListResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

type isGetIScsiSessionListResponse_Error interface {
	isGetIScsiSessionListResponse_Error()
}

type GetIScsiSessionListResponse_WindowsApiError struct {
	WindowsApiError *api.WindowsApiError `protobuf:"bytes,2,opt,name=windows_api_error,json=windowsApiError,proto3,oneof"`
}

type GetIScsiSessionListResponse_ErrorMessage struct {
	ErrorMessage string `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3,oneof"`
}

func (*GetIScsiSessionListResponse_WindowsApiError) isGetIScsiSessionListResponse_Error() {}

func (*GetIScsiSessionListResponse_ErrorMessage) isGetIScsiSessionListResponse_Error() {}

func (m *GetIScsiSessionListResponse) GetError() isGetIScsiSessionListResponse_Error {
	if m != nil {
		return m.Error
	}
	return nil
}

func (m *GetIScsiSessionListResponse) GetWindowsApiError() *api.WindowsApiError {
	if x, ok := m.GetError().(*GetIScsiSessionListResponse_WindowsApiError); ok {
		return x.WindowsApiError
	}
	return nil
}

func (m *GetIScsiSessionListResponse) GetErrorMessage() string {
	if x, ok := m.GetError().(*GetIScsiSessionListResponse_ErrorMessage); ok {
		return x.ErrorMessage
	}
	return ""
}

func (m *GetIScsiSessionListResponse) GetSessionInfos() []*IscsiSessionInfo {
	if m != nil {
		return m.SessionInfos
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*GetIScsiSessionListResponse) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*GetIScsiSessionListResponse_WindowsApiError)(nil),
		(*GetIScsiSessionListResponse_ErrorMessage)(nil),
	}
}

type GetDevicesForIScsiSessionRequest struct {
	SessionId            *IscsiID `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetDevicesForIScsiSessionRequest) Reset()         { *m = GetDevicesForIScsiSessionRequest{} }
func (m *GetDevicesForIScsiSessionRequest) String() string { return proto.CompactTextString(m) }
func (*GetDevicesForIScsiSessionRequest) ProtoMessage()    {}
func (*GetDevicesForIScsiSessionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_954acfae42d1ccbb, []int{22}
}

func (m *GetDevicesForIScsiSessionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetDevicesForIScsiSessionRequest.Unmarshal(m, b)
}
func (m *GetDevicesForIScsiSessionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetDevicesForIScsiSessionRequest.Marshal(b, m, deterministic)
}
func (m *GetDevicesForIScsiSessionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetDevicesForIScsiSessionRequest.Merge(m, src)
}
func (m *GetDevicesForIScsiSessionRequest) XXX_Size() int {
	return xxx_messageInfo_GetDevicesForIScsiSessionRequest.Size(m)
}
func (m *GetDevicesForIScsiSessionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetDevicesForIScsiSessionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetDevicesForIScsiSessionRequest proto.InternalMessageInfo

func (m *GetDevicesForIScsiSessionRequest) GetSessionId() *IscsiID {
	if m != nil {
		return m.SessionId
	}
	return nil
}

// see https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/content/ntddscsi/ns-ntddscsi-_scsi_address
type ScsiAddress struct {
	PortNumber           uint32   `protobuf:"varint,1,opt,name=port_number,json=portNumber,proto3" json:"port_number,omitempty"`
	PathId               uint32   `protobuf:"varint,2,opt,name=path_id,json=pathId,proto3" json:"path_id,omitempty"`
	TargetId             uint32   `protobuf:"varint,3,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"`
	Lun                  uint32   `protobuf:"varint,4,opt,name=lun,proto3" json:"lun,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ScsiAddress) Reset()         { *m = ScsiAddress{} }
func (m *ScsiAddress) String() string { return proto.CompactTextString(m) }
func (*ScsiAddress) ProtoMessage()    {}
func (*ScsiAddress) Descriptor() ([]byte, []int) {
	return fileDescriptor_954acfae42d1ccbb, []int{23}
}

func (m *ScsiAddress) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ScsiAddress.Unmarshal(m, b)
}
func (m *ScsiAddress) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ScsiAddress.Marshal(b, m, deterministic)
}
func (m *ScsiAddress) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ScsiAddress.Merge(m, src)
}
func (m *ScsiAddress) XXX_Size() int {
	return xxx_messageInfo_ScsiAddress.Size(m)
}
func (m *ScsiAddress) XXX_DiscardUnknown() {
	xxx_messageInfo_ScsiAddress.DiscardUnknown(m)
}

var xxx_messageInfo_ScsiAddress proto.InternalMessageInfo

func (m *ScsiAddress) GetPortNumber() uint32 {
	if m != nil {
		return m.PortNumber
	}
	return 0
}

func (m *ScsiAddress) GetPathId() uint32 {
	if m != nil {
		return m.PathId
	}
	return 0
}

func (m *ScsiAddress) GetTargetId() uint32 {
	if m != nil {
		return m.TargetId
	}
	return 0
}

func (m *ScsiAddress) GetLun() uint32 {
	if m != nil {
		return m.Lun
	}
	return 0
}

// see https://docs.microsoft.com/en-us/windows/win32/api/winioctl/ns-winioctl-_storage_device_number
type IscsiStorageDeviceNumber struct {
	DeviceType           uint32   `protobuf:"varint,1,opt,name=device_type,json=deviceType,proto3" json:"device_type,omitempty"`
	DeviceNumber         uint32   `protobuf:"varint,2,opt,name=device_number,json=deviceNumber,proto3" json:"device_number,omitempty"`
	PartitionNumber      uint32   `protobuf:"varint,3,opt,name=partition_number,json=partitionNumber,proto3" json:"partition_number,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IscsiStorageDeviceNumber) Reset()         { *m = IscsiStorageDeviceNumber{} }
func (m *IscsiStorageDeviceNumber) String() string { return proto.CompactTextString(m) }
func (*IscsiStorageDeviceNumber) ProtoMessage()    {}
func (*IscsiStorageDeviceNumber) Descriptor() ([]byte, []int) {
	return fileDescriptor_954acfae42d1ccbb, []int{24}
}

func (m *IscsiStorageDeviceNumber) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IscsiStorageDeviceNumber.Unmarshal(m, b)
}
func (m *IscsiStorageDeviceNumber) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IscsiStorageDeviceNumber.Marshal(b, m, deterministic)
}
func (m *IscsiStorageDeviceNumber) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IscsiStorageDeviceNumber.Merge(m, src)
}
func (m *IscsiStorageDeviceNumber) XXX_Size() int {
	return xxx_messageInfo_IscsiStorageDeviceNumber.Size(m)
}
func (m *IscsiStorageDeviceNumber) XXX_DiscardUnknown() {
	xxx_messageInfo_IscsiStorageDeviceNumber.DiscardUnknown(m)
}

var xxx_messageInfo_IscsiStorageDeviceNumber proto.InternalMessageInfo

func (m *IscsiStorageDeviceNumber) GetDeviceType() uint32 {
	if m != nil {
		return m.DeviceType
	}
	return 0
}

func (m *IscsiStorageDeviceNumber) GetDeviceNumber() uint32 {
	if m != nil {
		return m.DeviceNumber
	}
	return 0
}

func (m *IscsiStorageDeviceNumber) GetPartitionNumber() uint32 {
	if m != nil {
		return m.PartitionNumber
	}
	return 0
}

// see https://docs.microsoft.com/en-us/windows/win32/api/iscsidsc/ns-iscsidsc-iscsi_device_on_sessionw
type IscsiDevice struct {
	InitiatorName        string                    `protobuf:"bytes,1,opt,name=initiator_name,json=initiatorName,proto3" json:"initiator_name,omitempty"`
	TargetName           string                    `protobuf:"bytes,2,opt,name=target_name,json=targetName,proto3" json:"target_name,omitempty"`
	ScsiAddress          *ScsiAddress              `protobuf:"bytes,3,opt,name=scsi_address,json=scsiAddress,proto3" json:"scsi_address,omitempty"`
	DeviceInterfaceType  string                    `protobuf:"bytes,4,opt,name=device_interface_type,json=deviceInterfaceType,proto3" json:"device_interface_type,omitempty"`
	DeviceInterfaceName  string                    `protobuf:"bytes,5,opt,name=device_interface_name,json=deviceInterfaceName,proto3" json:"device_interface_name,omitempty"`
	LegacyName           string                    `protobuf:"bytes,6,opt,name=legacy_name,json=legacyName,proto3" json:"legacy_name,omitempty"`
	StorageDeviceNumber  *IscsiStorageDeviceNumber `protobuf:"bytes,7,opt,name=storage_device_number,json=storageDeviceNumber,proto3" json:"storage_device_number,omitempty"`
	DeviceInstance       uint32                    `protobuf:"varint,8,opt,name=device_instance,json=deviceInstance,proto3" json:"device_instance,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *IscsiDevice) Reset()         { *m = IscsiDevice{} }
func (m *IscsiDevice) String() string { return proto.CompactTextString(m) }
func (*IscsiDevice) ProtoMessage()    {}
func (*IscsiDevice) Descriptor() ([]byte, []int) {
	return fileDescriptor_954acfae42d1ccbb, []int{25}
}

func (m *IscsiDevice) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IscsiDevice.Unmarshal(m, b)
}
func (m *IscsiDevice) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IscsiDevice.Marshal(b, m, deterministic)
}
func (m *IscsiDevice) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IscsiDevice.Merge(m, src)
}
func (m *IscsiDevice) XXX_Size() int {
	return xxx_messageInfo_IscsiDevice.Size(m)
}
func (m *IscsiDevice) XXX_DiscardUnknown() {
	xxx_messageInfo_IscsiDevice.DiscardUnknown(m)
}

var xxx_messageInfo_IscsiDevice proto.InternalMessageInfo

func (m *IscsiDevice) GetInitiatorName() string {
	if m != nil {
		return m.InitiatorName
	}
	return ""
}

func (m *IscsiDevice) GetTargetName() string {
	if m != nil {
		return m.TargetName
	}
	return ""
}

func (m *IscsiDevice) GetScsiAddress() *ScsiAddress {
	if m != nil {
		return m.ScsiAddress
	}
	return nil
}

func (m *IscsiDevice) GetDeviceInterfaceType() string {
	if m != nil {
		return m.DeviceInterfaceType
	}
	return ""
}

func (m *IscsiDevice) GetDeviceInterfaceName() string {
	if m != nil {
		return m.DeviceInterfaceName
	}
	return ""
}

func (m *IscsiDevice) GetLegacyName() string {
	if m != nil {
		return m.LegacyName
	}
	return ""
}

func (m *IscsiDevice) GetStorageDeviceNumber() *IscsiStorageDeviceNumber {
	if m != nil {
		return m.StorageDeviceNumber
	}
	return nil
}

func (m *IscsiDevice) GetDeviceInstance() uint32 {
	if m != nil {
		return m.DeviceInstance
	}
	return 0
}

type GetDevicesForIScsiSessionResponse struct {
	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	// Types that are valid to be assigned to Error:
	//	*GetDevicesForIScsiSessionResponse_WindowsApiError
	//	*GetDevicesForIScsiSessionResponse_ErrorMessage
	Error                isGetDevicesForIScsiSessionResponse_Error `protobuf_oneof:"error"`
	Devices              []*IscsiDevice                            `protobuf:"bytes,4,rep,name=devices,proto3" json:"devices,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                                  `json:"-"`
	XXX_unrecognized     []byte                                    `json:"-"`
	XXX_sizecache        int32                                     `json:"-"`
}

func (m *GetDevicesForIScsiSessionResponse) Reset()         { *m = GetDevicesForIScsiSessionResponse{} }
func (m *GetDevicesForIScsiSessionResponse) String() string { return proto.CompactTextString(m) }
func (*GetDevicesForIScsiSessionResponse) ProtoMessage()    {}
func (*GetDevicesForIScsiSessionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_954acfae42d1ccbb, []int{26}
}

func (m *GetDevicesForIScsiSessionResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetDevicesForIScsiSessionResponse.Unmarshal(m, b)
}
func (m *GetDevicesForIScsiSessionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetDevicesForIScsiSessionResponse.Marshal(b, m, deterministic)
}
func (m *GetDevicesForIScsiSessionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetDevicesForIScsiSessionResponse.Merge(m, src)
}
func (m *GetDevicesForIScsiSessionResponse) XXX_Size() int {
	return xxx_messageInfo_GetDevicesForIScsiSessionResponse.Size(m)
}
func (m *GetDevicesForIScsiSessionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetDevicesForIScsiSessionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetDevicesForIScsiSessionResponse proto.InternalMessageInfo

func (m *GetDevicesForIScsiSessionResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

type isGetDevicesForIScsiSessionResponse_Error interface {
	isGetDevicesForIScsiSessionResponse_Error()
}

type GetDevicesForIScsiSessionResponse_WindowsApiError struct {
	WindowsApiError *api.WindowsApiError `protobuf:"bytes,2,opt,name=windows_api_error,json=windowsApiError,proto3,oneof"`
}

type GetDevicesForIScsiSessionResponse_ErrorMessage struct {
	ErrorMessage string `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3,oneof"`
}

func (*GetDevicesForIScsiSessionResponse_WindowsApiError) isGetDevicesForIScsiSessionResponse_Error() {
}

func (*GetDevicesForIScsiSessionResponse_ErrorMessage) isGetDevicesForIScsiSessionResponse_Error() {}

func (m *GetDevicesForIScsiSessionResponse) GetError() isGetDevicesForIScsiSessionResponse_Error {
	if m != nil {
		return m.Error
	}
	return nil
}

func (m *GetDevicesForIScsiSessionResponse) GetWindowsApiError() *api.WindowsApiError {
	if x, ok := m.GetError().(*GetDevicesForIScsiSessionResponse_WindowsApiError); ok {
		return x.WindowsApiError
	}
	return nil
}

func (m *GetDevicesForIScsiSessionResponse) GetErrorMessage() string {
	if x, ok := m.GetError().(*GetDevicesForIScsiSessionResponse_ErrorMessage); ok {
		return x.ErrorMessage
	}
	return ""
}

func (m *GetDevicesForIScsiSessionResponse) GetDevices() []*IscsiDevice {
	if m != nil {
		return m.Devices
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*GetDevicesForIScsiSessionResponse) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*GetDevicesForIScsiSessionResponse_WindowsApiError)(nil),
		(*GetDevicesForIScsiSessionResponse_ErrorMessage)(nil),
	}
}

func init() {
	proto.RegisterEnum("IscsiAuthType", IscsiAuthType_name, IscsiAuthType_value)
	proto.RegisterEnum("IscsiDigestType", IscsiDigestType_name, IscsiDigestType_value)
	proto.RegisterType((*MountISCSILunRequest)(nil), "MountISCSILunRequest")
	proto.RegisterType((*MountISCSILunResponse)(nil), "MountISCSILunResponse")
	proto.RegisterType((*ReportIScsiSendTargetPortalsRequest)(nil), "ReportIScsiSendTargetPortalsRequest")
	proto.RegisterType((*IscsiPortal)(nil), "IscsiPortal")
	proto.RegisterType((*IscsiLoginOptions)(nil), "IscsiLoginOptions")
	proto.RegisterType((*IscsiPortalInfo)(nil), "IscsiPortalInfo")
	proto.RegisterType((*ReportIScsiSendTargetPortalsResponse)(nil), "ReportIScsiSendTargetPortalsResponse")
	proto.RegisterType((*AddIScsiSendTargetPortalRequest)(nil), "AddIScsiSendTargetPortalRequest")
	proto.RegisterType((*AddIScsiSendTargetPortalResponse)(nil), "AddIScsiSendTargetPortalResponse")
	proto.RegisterType((*RemoveIScsiSendTargetPortalRequest)(nil), "RemoveIScsiSendTargetPortalRequest")
	proto.RegisterType((*RemoveIScsiSendTargetPortalResponse)(nil), "RemoveIScsiSendTargetPortalResponse")
	proto.RegisterType((*ReportIScsiTargetsRequest)(nil), "ReportIScsiTargetsRequest")
	proto.RegisterType((*ReportIScsiTargetsResponse)(nil), "ReportIScsiTargetsResponse")
	proto.RegisterType((*LoginIscsiTargetRequest)(nil), "LoginIscsiTargetRequest")
	proto.RegisterType((*IscsiID)(nil), "IscsiID")
	proto.RegisterType((*LoginIscsiTargetResponse)(nil), "LoginIscsiTargetResponse")
	proto.RegisterType((*LogoutIScsiTargetRequest)(nil), "LogoutIScsiTargetRequest")
	proto.RegisterType((*LogoutIScsiTargetResponse)(nil), "LogoutIScsiTargetResponse")
	proto.RegisterType((*GetIScsiSessionListRequest)(nil), "GetIScsiSessionListRequest")
	proto.RegisterType((*IscsiConnectionInfo)(nil), "IscsiConnectionInfo")
	proto.RegisterType((*IscsiSessionInfo)(nil), "IscsiSessionInfo")
	proto.RegisterType((*GetIScsiSessionListResponse)(nil), "GetIScsiSessionListResponse")
	proto.RegisterType((*GetDevicesForIScsiSessionRequest)(nil), "GetDevicesForIScsiSessionRequest")
	proto.RegisterType((*ScsiAddress)(nil), "ScsiAddress")
	proto.RegisterType((*IscsiStorageDeviceNumber)(nil), "IscsiStorageDeviceNumber")
	proto.RegisterType((*IscsiDevice)(nil), "IscsiDevice")
	proto.RegisterType((*GetDevicesForIScsiSessionResponse)(nil), "GetDevicesForIScsiSessionResponse")
}

func init() { proto.RegisterFile("iscsi.proto", fileDescriptor_954acfae42d1ccbb) }

var fileDescriptor_954acfae42d1ccbb = []byte{
	// 1746 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0x58, 0x4f, 0x73, 0x1b, 0x49,
	0x15, 0xcf, 0x58, 0xb6, 0x25, 0xbf, 0x99, 0xb1, 0xe5, 0xf6, 0x7a, 0xa3, 0x64, 0xa9, 0xb2, 0x33,
	0xd9, 0xb0, 0xce, 0x06, 0xcb, 0xb5, 0x0a, 0x04, 0x8a, 0x43, 0xaa, 0x8c, 0xcc, 0x6e, 0xa6, 0x48,
	0xbc, 0xa9, 0x56, 0x52, 0x39, 0x70, 0x98, 0x6a, 0xcf, 0xb4, 0xe5, 0xae, 0x48, 0xd3, 0x93, 0xe9,
	0x19, 0x7b, 0xf5, 0x09, 0xa8, 0x82, 0xe2, 0xca, 0x9d, 0x03, 0x37, 0x28, 0xbe, 0x03, 0x37, 0x3e,
	0x00, 0x67, 0x4e, 0x7c, 0x01, 0x8e, 0xc0, 0x81, 0xea, 0x3f, 0xf3, 0x47, 0xb2, 0x64, 0x9c, 0x13,
	0xba, 0xd8, 0xea, 0xf7, 0xa7, 0xe7, 0xf5, 0xfb, 0xfd, 0xde, 0x9b, 0xd7, 0x03, 0x36, 0x13, 0xa1,
	0x60, 0xdd, 0x24, 0xe5, 0x19, 0xbf, 0xff, 0xc3, 0x21, 0xcb, 0x2e, 0xf2, 0xb3, 0x6e, 0xc8, 0xc7,
	0x47, 0xef, 0xf3, 0x33, 0x9a, 0xc6, 0x34, 0xa3, 0xe2, 0x30, 0x14, 0xec, 0x28, 0x14, 0xec, 0x30,
	0x49, 0xf9, 0x77, 0x93, 0x23, 0x92, 0xb0, 0x23, 0x9a, 0xa6, 0x3c, 0x15, 0xda, 0xcb, 0xfb, 0x77,
	0x03, 0x3e, 0x79, 0xc5, 0xf3, 0x38, 0xf3, 0x07, 0xfd, 0x81, 0xff, 0x32, 0x8f, 0x31, 0xfd, 0x90,
	0x53, 0x91, 0xa1, 0x7b, 0xd0, 0x8a, 0x79, 0x44, 0x03, 0xf6, 0x21, 0xee, 0x58, 0xfb, 0xd6, 0xc1,
	0x06, 0x6e, 0xca, 0xb5, 0xff, 0x21, 0x46, 0xcf, 0x61, 0x27, 0x62, 0x22, 0xe4, 0x97, 0x34, 0x9d,
	0x04, 0x24, 0xcf, 0x2e, 0x82, 0x6c, 0x92, 0xd0, 0xce, 0xca, 0xbe, 0x75, 0xb0, 0xd9, 0xdb, 0xec,
	0xfa, 0x32, 0xa8, 0xe3, 0x3c, 0xbb, 0x78, 0x33, 0x49, 0x28, 0xde, 0x2e, 0x4d, 0x0b, 0x11, 0x7a,
	0x06, 0x77, 0x2b, 0xff, 0xf0, 0x82, 0x24, 0x41, 0x2e, 0x68, 0x1a, 0x93, 0x31, 0xed, 0x34, 0xd4,
	0x93, 0x76, 0x4b, 0x75, 0xff, 0x82, 0x24, 0x6f, 0x8d, 0x12, 0xf5, 0x60, 0x77, 0xc6, 0x4f, 0xd0,
	0x30, 0xa5, 0x59, 0x67, 0x55, 0x79, 0xed, 0x4c, 0x79, 0x0d, 0x94, 0x0a, 0xfd, 0x14, 0xb6, 0x05,
	0x15, 0x82, 0xf1, 0xb8, 0x16, 0xe9, 0xda, 0xdc, 0x48, 0xb7, 0x8c, 0x61, 0x19, 0x67, 0x0f, 0x76,
	0x0b, 0xdf, 0xe9, 0x28, 0xd7, 0xf5, 0xf3, 0x8c, 0x72, 0x2a, 0xc6, 0x2e, 0xec, 0x4c, 0xf9, 0x98,
	0x08, 0x9b, 0xca, 0x63, 0xbb, 0xe6, 0x61, 0xe2, 0xeb, 0xc1, 0x6e, 0x46, 0xd2, 0x21, 0xcd, 0x82,
	0x84, 0xa7, 0x19, 0x19, 0x05, 0x24, 0x8a, 0x52, 0x2a, 0x44, 0xa7, 0xa5, 0x9f, 0xa1, 0x95, 0xaf,
	0x95, 0xee, 0x58, 0xab, 0xd0, 0x0f, 0x00, 0x4d, 0xfb, 0xc8, 0x7f, 0x9d, 0x8d, 0x7d, 0xeb, 0xc0,
	0xc5, 0xed, 0xba, 0x83, 0xfc, 0x8b, 0xee, 0x43, 0x2b, 0xa5, 0x24, 0xe2, 0xf1, 0x68, 0xd2, 0x81,
	0x7d, 0xeb, 0xa0, 0x85, 0xcb, 0xb5, 0xf7, 0x17, 0x0b, 0x76, 0x67, 0xd0, 0x17, 0x09, 0x8f, 0x05,
	0x45, 0x1d, 0x68, 0x8a, 0x3c, 0x0c, 0x65, 0x24, 0x96, 0x72, 0x2a, 0x96, 0xe8, 0x39, 0x6c, 0x5f,
	0xb1, 0x38, 0xe2, 0x57, 0x22, 0x20, 0x09, 0x0b, 0x14, 0x9b, 0x14, 0xf6, 0x76, 0xaf, 0xdd, 0x7d,
	0xa7, 0x35, 0xc7, 0x09, 0xfb, 0xb9, 0x94, 0xbf, 0xb8, 0x83, 0xb7, 0xae, 0xa6, 0x45, 0xe8, 0x11,
	0xb8, 0xca, 0x27, 0x18, 0x53, 0x21, 0xc8, 0xd0, 0x60, 0xfe, 0xe2, 0x0e, 0x76, 0x94, 0xf8, 0x95,
	0x96, 0xa2, 0x3d, 0xb0, 0x23, 0x26, 0xde, 0x07, 0x71, 0x3e, 0x3e, 0xa3, 0xa9, 0x82, 0xd8, 0xc5,
	0x20, 0x45, 0xa7, 0x4a, 0xf2, 0xb3, 0x26, 0xac, 0x29, 0x07, 0xef, 0x11, 0x3c, 0xc4, 0x54, 0xa6,
	0xc0, 0x1f, 0x84, 0x82, 0x0d, 0x68, 0x1c, 0xbd, 0xa9, 0xe5, 0x40, 0x18, 0x42, 0x7b, 0x11, 0xd8,
	0x0a, 0x6f, 0x2d, 0x46, 0x0f, 0xc1, 0x15, 0x93, 0xf1, 0x19, 0x1f, 0xb1, 0x30, 0x50, 0xa0, 0x6a,
	0x92, 0x3b, 0x85, 0xf0, 0x54, 0xa2, 0xd9, 0x81, 0x66, 0x81, 0xc7, 0x8a, 0xae, 0x01, 0xb3, 0x44,
	0x9f, 0xc2, 0xba, 0xe0, 0xe1, 0x7b, 0x9a, 0xa9, 0xf0, 0x5d, 0x6c, 0x56, 0xde, 0xef, 0x1a, 0xb0,
	0xad, 0x1e, 0xf3, 0x92, 0x0f, 0x59, 0xfc, 0x6d, 0x92, 0x31, 0x1e, 0x0b, 0x79, 0x98, 0x91, 0x5c,
	0x07, 0xe7, 0x23, 0x32, 0xd4, 0x19, 0x75, 0x31, 0x28, 0xd1, 0xd7, 0x52, 0x82, 0x9e, 0xc0, 0xc6,
	0xff, 0x2a, 0xa4, 0x16, 0x29, 0x78, 0xf9, 0x23, 0x70, 0x2f, 0x28, 0x89, 0x68, 0x1a, 0x44, 0x6c,
	0x48, 0x85, 0x0e, 0x61, 0xb3, 0xd7, 0xd6, 0x0e, 0x27, 0x4a, 0xa6, 0x5c, 0x1c, 0x6d, 0xa6, 0x25,
	0xe8, 0x2b, 0xb0, 0x23, 0x92, 0x91, 0xc2, 0x69, 0x75, 0x81, 0x13, 0x48, 0x23, 0xe3, 0x72, 0x04,
	0x3b, 0x63, 0xf2, 0x1d, 0x1b, 0xe7, 0xe3, 0x20, 0xe4, 0x71, 0x4c, 0x43, 0x75, 0x1c, 0x55, 0x3f,
	0x2e, 0x46, 0x46, 0xd5, 0xaf, 0x34, 0xe8, 0x10, 0x76, 0x22, 0x7a, 0x4e, 0xf2, 0x51, 0x16, 0x64,
	0x6c, 0x4c, 0x83, 0x5e, 0x70, 0x45, 0x58, 0xa6, 0x0a, 0xc6, 0xc5, 0x6d, 0xa3, 0x7a, 0xc3, 0xc6,
	0xb4, 0xf7, 0x8e, 0x30, 0x19, 0xd2, 0xee, 0x8c, 0x79, 0x4a, 0x33, 0xc2, 0x62, 0x55, 0x2f, 0x2e,
	0x46, 0x75, 0x07, 0xac, 0x34, 0x92, 0xce, 0x65, 0x1d, 0xea, 0x1a, 0x29, 0xd7, 0x52, 0x97, 0x10,
	0x21, 0xae, 0x78, 0x1a, 0xa9, 0x72, 0xd8, 0xc0, 0xe5, 0xda, 0xfb, 0xa7, 0x05, 0x5b, 0x35, 0xfc,
	0xfd, 0xf8, 0x9c, 0xa3, 0xcf, 0x61, 0x5d, 0x57, 0x90, 0x42, 0xc4, 0xee, 0x39, 0xdd, 0x9a, 0x05,
	0x36, 0x3a, 0xf4, 0x08, 0x36, 0x59, 0xcc, 0x32, 0x46, 0x32, 0x9e, 0x6a, 0xaa, 0x68, 0x2e, 0xb8,
	0xa5, 0xf4, 0xd4, 0x74, 0xa7, 0xca, 0x4c, 0xba, 0x16, 0xd4, 0xd5, 0x04, 0xd9, 0x29, 0x95, 0x72,
	0x7b, 0xcd, 0x61, 0xb9, 0xb5, 0xa0, 0x61, 0x9e, 0xb2, 0x6c, 0x62, 0xa8, 0x21, 0x51, 0x59, 0xc5,
	0x6e, 0x21, 0xd5, 0xec, 0xf8, 0x31, 0xb8, 0x9a, 0x3e, 0x3c, 0xa9, 0x00, 0xb0, 0x7b, 0xa8, 0x7b,
	0x8d, 0x69, 0xd8, 0x19, 0xd5, 0x56, 0xde, 0x3f, 0x2c, 0xf8, 0xfc, 0xe6, 0xda, 0x58, 0x96, 0x72,
	0x7f, 0x0a, 0x8e, 0x69, 0x66, 0x2c, 0x3e, 0xe7, 0x32, 0x0f, 0x0d, 0xf5, 0x84, 0x19, 0xc8, 0xb0,
	0x9d, 0x94, 0xbf, 0x45, 0xd5, 0x02, 0x7e, 0xbd, 0x02, 0x7b, 0xc7, 0x51, 0x34, 0xf7, 0x90, 0xc5,
	0x0b, 0xed, 0x10, 0x50, 0x85, 0x0f, 0x8b, 0x45, 0x46, 0xe2, 0xb0, 0xa8, 0xfa, 0xed, 0x52, 0xe3,
	0x1b, 0xc5, 0x62, 0x38, 0x57, 0x16, 0xc3, 0x79, 0x0d, 0xa7, 0xc6, 0xed, 0x70, 0xba, 0x2d, 0x0f,
	0x2a, 0xbe, 0xae, 0x2d, 0xe6, 0xab, 0xf7, 0x47, 0x0b, 0xf6, 0x17, 0x27, 0x63, 0x49, 0x00, 0xaf,
	0xb0, 0xfb, 0x93, 0x05, 0x1e, 0xa6, 0x63, 0x7e, 0x49, 0xff, 0xdf, 0xf0, 0x55, 0xe9, 0x6d, 0xdc,
	0x90, 0xde, 0x3f, 0x5b, 0xf2, 0x7d, 0x73, 0x43, 0xbc, 0x4b, 0x97, 0xe1, 0xe7, 0x70, 0xaf, 0xd6,
	0x04, 0x74, 0xb0, 0xc5, 0x6b, 0x11, 0x3d, 0x00, 0xe7, 0x9c, 0xa7, 0x21, 0x0d, 0xf2, 0x24, 0x22,
	0x19, 0x35, 0xb1, 0xda, 0x4a, 0xf6, 0x56, 0x89, 0xbc, 0xbf, 0x5a, 0x70, 0x7f, 0xde, 0x06, 0xcb,
	0xd2, 0x3b, 0x1e, 0x80, 0x63, 0xe6, 0x21, 0xd9, 0x9d, 0x75, 0xef, 0xd8, 0xc0, 0xb6, 0x96, 0xc9,
	0xde, 0x5c, 0xeb, 0x14, 0xbf, 0x6f, 0xc0, 0x5d, 0x55, 0x88, 0x0a, 0x5a, 0x7d, 0x94, 0x22, 0x15,
	0x7b, 0x60, 0xd7, 0xf6, 0x31, 0xdc, 0x82, 0x6a, 0x1b, 0xf4, 0x13, 0xe8, 0x30, 0xa1, 0x1a, 0x54,
	0x3a, 0x26, 0xb2, 0x72, 0xc9, 0x28, 0x30, 0x23, 0x9d, 0x3a, 0x56, 0x0b, 0x7f, 0xca, 0x84, 0x5f,
	0x57, 0x0f, 0xb4, 0x76, 0x01, 0x7b, 0x1b, 0x1f, 0xcd, 0xde, 0xd5, 0xc5, 0xec, 0xfd, 0x0a, 0xdc,
	0xa9, 0xa9, 0x70, 0x6e, 0x8f, 0x70, 0xea, 0xe3, 0xe1, 0x9c, 0xb6, 0xb3, 0x7e, 0xab, 0xd7, 0x4f,
	0xf3, 0x96, 0x6d, 0xad, 0x0d, 0x8d, 0xf7, 0x74, 0x62, 0x5e, 0xd3, 0xf2, 0xa7, 0x9c, 0xba, 0x98,
	0x08, 0x12, 0x9a, 0x0a, 0x26, 0x32, 0x1a, 0xeb, 0xa9, 0xb5, 0x85, 0x1d, 0x26, 0x5e, 0x97, 0x32,
	0xef, 0x97, 0xd0, 0x54, 0x3b, 0xfb, 0x27, 0x32, 0x42, 0x12, 0x91, 0x24, 0xa3, 0x69, 0x90, 0xc7,
	0xec, 0x43, 0xae, 0x51, 0x59, 0xc5, 0xae, 0x91, 0xbe, 0x55, 0x42, 0xf4, 0x18, 0xda, 0x85, 0x99,
	0x48, 0x68, 0xc8, 0xce, 0x59, 0xa8, 0x00, 0x59, 0xc5, 0x5b, 0x46, 0x3e, 0x30, 0x62, 0xef, 0x3f,
	0x16, 0x74, 0xae, 0x13, 0x60, 0x59, 0xa8, 0xfc, 0x05, 0x40, 0x71, 0x7d, 0x60, 0x91, 0x42, 0xdb,
	0xee, 0xb5, 0xba, 0x26, 0x1b, 0x78, 0xc3, 0xe8, 0xfc, 0x08, 0x1d, 0x82, 0x5b, 0x4d, 0x64, 0xd2,
	0x76, 0x6d, 0xc6, 0xd6, 0xa9, 0xd4, 0x7e, 0x54, 0xf1, 0xbf, 0xaf, 0x4e, 0xcf, 0xf3, 0x7a, 0x29,
	0x17, 0xfc, 0x9f, 0x7e, 0xb8, 0xb5, 0xf0, 0xe1, 0xde, 0x1f, 0x2c, 0xb8, 0x37, 0x67, 0x97, 0xa5,
	0x6b, 0x7c, 0xdf, 0x83, 0xfb, 0xdf, 0xd0, 0x62, 0xf4, 0x51, 0xc1, 0xbf, 0x64, 0xa2, 0x38, 0xae,
	0xf7, 0x2f, 0x0b, 0x76, 0xd4, 0xe1, 0xaa, 0x01, 0x56, 0x4d, 0x85, 0xd7, 0x52, 0x6b, 0xdd, 0x94,
	0x5a, 0xf4, 0x04, 0xaa, 0x02, 0x0e, 0xa6, 0x6f, 0x0b, 0xed, 0x52, 0x51, 0x5c, 0xdd, 0x1e, 0xc1,
	0xa6, 0x29, 0xd2, 0xc2, 0x52, 0xf7, 0x00, 0x53, 0xba, 0x85, 0xd9, 0x63, 0xa8, 0x5c, 0x03, 0x73,
	0xcf, 0xd0, 0xa5, 0xbf, 0x55, 0xca, 0x07, 0x4a, 0x2c, 0x2b, 0xca, 0xec, 0x68, 0xec, 0xf4, 0x70,
	0x6e, 0x0a, 0xdd, 0x18, 0xb5, 0xa1, 0xd1, 0xf7, 0x4f, 0x54, 0x75, 0x3b, 0x58, 0xfe, 0xf4, 0x7e,
	0xbb, 0x02, 0x6d, 0x75, 0x1e, 0x93, 0x18, 0x75, 0xf2, 0xdb, 0x12, 0xe0, 0xb6, 0x23, 0xf1, 0x01,
	0xb4, 0x8b, 0x86, 0xca, 0x23, 0x1a, 0xd4, 0x6e, 0xf8, 0x26, 0x0b, 0xa7, 0x3c, 0xa2, 0xca, 0x72,
	0xa6, 0xf5, 0xae, 0x5e, 0x6b, 0xbd, 0x08, 0x56, 0xfd, 0x81, 0x7f, 0xa2, 0x4e, 0xe7, 0x60, 0xf5,
	0x5b, 0xca, 0xde, 0x0c, 0xca, 0x63, 0xa9, 0xdf, 0xe8, 0x19, 0xd8, 0xf5, 0x9b, 0x4a, 0x53, 0x8d,
	0x91, 0x9f, 0x74, 0xe7, 0xe0, 0x8c, 0xeb, 0x86, 0xde, 0xdf, 0x2d, 0xf8, 0x6c, 0x2e, 0x57, 0x96,
	0xa5, 0x33, 0x3c, 0x03, 0xb7, 0xc4, 0xa6, 0x36, 0x21, 0x6f, 0x77, 0x67, 0x51, 0xc4, 0x8e, 0xa8,
	0x16, 0xb5, 0x37, 0xdf, 0x2f, 0x60, 0xff, 0x1b, 0x9a, 0x9d, 0xd0, 0x4b, 0x16, 0x52, 0xf1, 0x35,
	0x4f, 0xeb, 0x47, 0xfd, 0xe8, 0x0e, 0x70, 0x09, 0xb6, 0x74, 0x2f, 0xf8, 0xba, 0x07, 0x76, 0xfd,
	0x2d, 0x65, 0xee, 0xb7, 0x49, 0xf5, 0x72, 0xba, 0x0b, 0xcd, 0x84, 0x64, 0x17, 0x72, 0x57, 0x3d,
	0x80, 0xad, 0xcb, 0xa5, 0x1f, 0xa1, 0xcf, 0x60, 0xc3, 0x00, 0xcf, 0x22, 0x73, 0x53, 0x6a, 0x69,
	0x81, 0x1f, 0x49, 0xda, 0x8e, 0xf2, 0xd8, 0x30, 0x5f, 0xfe, 0xf4, 0x7e, 0x63, 0x41, 0x47, 0x1f,
	0x38, 0xe3, 0x29, 0x19, 0x52, 0x7d, 0x1c, 0xf3, 0x90, 0x3d, 0xb0, 0x23, 0xb5, 0xd6, 0xd7, 0x68,
	0x13, 0x85, 0x16, 0xa9, 0x8b, 0xf3, 0x43, 0x70, 0x8d, 0xc1, 0xd4, 0x30, 0xe8, 0x44, 0xf5, 0x5d,
	0x1e, 0x43, 0x3b, 0x21, 0x69, 0xc6, 0x54, 0xf5, 0x4f, 0x5d, 0xe1, 0xb6, 0x4a, 0xb9, 0x36, 0xf5,
	0x7e, 0xd5, 0x30, 0xdf, 0x14, 0x74, 0x18, 0x73, 0xca, 0xc2, 0x9a, 0x57, 0x16, 0x33, 0x64, 0x5f,
	0xb9, 0x46, 0xf6, 0x23, 0x70, 0xe4, 0xae, 0x53, 0x3d, 0x42, 0xbe, 0xc9, 0x6b, 0x29, 0xc7, 0xb6,
	0xa8, 0xe5, 0xbf, 0x27, 0xef, 0xd1, 0xea, 0x60, 0x2c, 0xce, 0x68, 0x7a, 0x4e, 0x8a, 0x1c, 0x14,
	0x5f, 0xc6, 0x94, 0xd2, 0x2f, 0x74, 0xc5, 0xd7, 0xad, 0x6b, 0x3e, 0x2a, 0x9e, 0xb5, 0xb9, 0x3e,
	0x45, 0xe4, 0x23, 0x3a, 0x24, 0xe1, 0x24, 0xa8, 0x7d, 0x07, 0x03, 0x2d, 0x52, 0x06, 0xaf, 0x60,
	0x57, 0x68, 0x64, 0x82, 0xe9, 0x4c, 0xeb, 0x91, 0xe1, 0x5e, 0x77, 0x11, 0x78, 0x78, 0x47, 0xcc,
	0x41, 0xf4, 0x0b, 0xd8, 0x2a, 0x63, 0x34, 0x33, 0x53, 0x4b, 0x41, 0xb1, 0x59, 0x44, 0xa7, 0xa5,
	0xde, 0xdf, 0x2c, 0x78, 0x70, 0x03, 0xbb, 0x97, 0xa5, 0x88, 0xbf, 0x0f, 0x4d, 0x1d, 0x78, 0x51,
	0xbe, 0x66, 0x3a, 0xd3, 0x71, 0xe3, 0x42, 0x59, 0x16, 0xed, 0x97, 0x4f, 0xc0, 0x9d, 0xfa, 0x0a,
	0x84, 0x00, 0xd6, 0x4f, 0xb9, 0x5c, 0xb5, 0xef, 0xa0, 0x4d, 0x80, 0x6f, 0x63, 0xfa, 0x8e, 0x4c,
	0xfa, 0x2f, 0x8e, 0x5f, 0xb7, 0xad, 0x2f, 0x9f, 0x98, 0x2f, 0x1c, 0xd5, 0xc7, 0x1c, 0xe4, 0x40,
	0xeb, 0x94, 0xeb, 0x75, 0xfb, 0x8e, 0x74, 0xee, 0xe3, 0xfe, 0xd3, 0x5e, 0xbf, 0x6d, 0x9d, 0xad,
	0xab, 0xef, 0xbf, 0x4f, 0xff, 0x1b, 0x00, 0x00, 0xff, 0xff, 0xc9, 0xc2, 0x48, 0x56, 0x44, 0x16,
	0x00, 0x00,
}
