// Code generated by protoc-gen-go. DO NOT EDIT.
// source: smb.proto

package smb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	api "github.com/kubernetes-csi/csi-proxy/api"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type MountSMBShareRequest struct {
	// A remote SMB share to mount
	// All unicode characters allowed in SMB server name specifications are
	// permitted except for restrictions below
	//
	// Restrictions:
	// SMB share specified in the format: \\server-name\sharename, \\server.fqdn\sharename or \\a.b.c.d\sharename
	// If not an IP address, server-name has to be a valid DNS name.
	// UNC specifications to local paths or prefix: \\?\ is not allowed.
	// Characters: + [ ] " / : ; | < > , ? * = $ are not allowed.
	RemoteShare string `protobuf:"bytes,1,opt,name=remote_share,json=remoteShare,proto3" json:"remote_share,omitempty"`
	// Local path in the host to stage the SMB share.
	// All special characters allowed by Windows in path names will be allowed
	// except for restrictions noted below. For details, please check:
	// https://docs.microsoft.com/en-us/windows/win32/fileio/naming-a-file
	//
	// Restrictions:
	// If given an absolute path, it needs to be under kubelet-csi-plugins-path,
	// and specified with drive letter prefix: "X:\".
	// If given a relative path, it will be understood as being relative to
	// kubelet-csi-plugins-path.
	// Needs to already exist on host.
	// UNC paths of the form "\\server\share\path\file" are not allowed.
	// All directory separators need to be backslash character: "\".
	// Characters: .. / : | ? * in the path are not allowed.
	// Maximum path length will be capped to 260 characters (MAX_PATH).
	HostPath string `protobuf:"bytes,2,opt,name=host_path,json=hostPath,proto3" json:"host_path,omitempty"`
	// Mount the share read-only.
	Readonly bool `protobuf:"varint,3,opt,name=readonly,proto3" json:"readonly,omitempty"`
	// Username credential associated with the share.
	Username string `protobuf:"bytes,4,opt,name=username,proto3" json:"username,omitempty"`
	// Password credential associated with the share.
	Password             string   `protobuf:"bytes,5,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MountSMBShareRequest) Reset()         { *m = MountSMBShareRequest{} }
func (m *MountSMBShareRequest) String() string { return proto.CompactTextString(m) }
func (*MountSMBShareRequest) ProtoMessage()    {}
func (*MountSMBShareRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_578488a9f93afe3f, []int{0}
}

func (m *MountSMBShareRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MountSMBShareRequest.Unmarshal(m, b)
}
func (m *MountSMBShareRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MountSMBShareRequest.Marshal(b, m, deterministic)
}
func (m *MountSMBShareRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MountSMBShareRequest.Merge(m, src)
}
func (m *MountSMBShareRequest) XXX_Size() int {
	return xxx_messageInfo_MountSMBShareRequest.Size(m)
}
func (m *MountSMBShareRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MountSMBShareRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MountSMBShareRequest proto.InternalMessageInfo

func (m *MountSMBShareRequest) GetRemoteShare() string {
	if m != nil {
		return m.RemoteShare
	}
	return ""
}

func (m *MountSMBShareRequest) GetHostPath() string {
	if m != nil {
		return m.HostPath
	}
	return ""
}

func (m *MountSMBShareRequest) GetReadonly() bool {
	if m != nil {
		return m.Readonly
	}
	return false
}

func (m *MountSMBShareRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *MountSMBShareRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type MountSMBShareResponse struct {
	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	// Types that are valid to be assigned to Error:
	//	*MountSMBShareResponse_CmdletError
	//	*MountSMBShareResponse_ErrorMessage
	Error                isMountSMBShareResponse_Error `protobuf_oneof:"error"`
	XXX_NoUnkeyedLiteral struct{}                      `json:"-"`
	XXX_unrecognized     []byte                        `json:"-"`
	XXX_sizecache        int32                         `json:"-"`
}

func (m *MountSMBShareResponse) Reset()         { *m = MountSMBShareResponse{} }
func (m *MountSMBShareResponse) String() string { return proto.CompactTextString(m) }
func (*MountSMBShareResponse) ProtoMessage()    {}
func (*MountSMBShareResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_578488a9f93afe3f, []int{1}
}

func (m *MountSMBShareResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MountSMBShareResponse.Unmarshal(m, b)
}
func (m *MountSMBShareResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MountSMBShareResponse.Marshal(b, m, deterministic)
}
func (m *MountSMBShareResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MountSMBShareResponse.Merge(m, src)
}
func (m *MountSMBShareResponse) XXX_Size() int {
	return xxx_messageInfo_MountSMBShareResponse.Size(m)
}
func (m *MountSMBShareResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MountSMBShareResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MountSMBShareResponse proto.InternalMessageInfo

func (m *MountSMBShareResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

type isMountSMBShareResponse_Error interface {
	isMountSMBShareResponse_Error()
}

type MountSMBShareResponse_CmdletError struct {
	CmdletError *api.CmdletError `protobuf:"bytes,2,opt,name=cmdlet_error,json=cmdletError,proto3,oneof"`
}

type MountSMBShareResponse_ErrorMessage struct {
	ErrorMessage string `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3,oneof"`
}

func (*MountSMBShareResponse_CmdletError) isMountSMBShareResponse_Error() {}

func (*MountSMBShareResponse_ErrorMessage) isMountSMBShareResponse_Error() {}

func (m *MountSMBShareResponse) GetError() isMountSMBShareResponse_Error {
	if m != nil {
		return m.Error
	}
	return nil
}

func (m *MountSMBShareResponse) GetCmdletError() *api.CmdletError {
	if x, ok := m.GetError().(*MountSMBShareResponse_CmdletError); ok {
		return x.CmdletError
	}
	return nil
}

func (m *MountSMBShareResponse) GetErrorMessage() string {
	if x, ok := m.GetError().(*MountSMBShareResponse_ErrorMessage); ok {
		return x.ErrorMessage
	}
	return ""
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*MountSMBShareResponse) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*MountSMBShareResponse_CmdletError)(nil),
		(*MountSMBShareResponse_ErrorMessage)(nil),
	}
}

func init() {
	proto.RegisterType((*MountSMBShareRequest)(nil), "MountSMBShareRequest")
	proto.RegisterType((*MountSMBShareResponse)(nil), "MountSMBShareResponse")
}

func init() { proto.RegisterFile("smb.proto", fileDescriptor_578488a9f93afe3f) }

var fileDescriptor_578488a9f93afe3f = []byte{
	// 324 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x91, 0xd1, 0x4a, 0xc3, 0x30,
	0x14, 0x86, 0x57, 0x75, 0xae, 0xcd, 0xba, 0x9b, 0xe0, 0xa4, 0xcc, 0x9b, 0x39, 0x10, 0x76, 0xb3,
	0x16, 0xa7, 0x0f, 0x20, 0x1b, 0xc2, 0xbc, 0x18, 0x8c, 0x16, 0xbc, 0x2d, 0x69, 0x76, 0x58, 0x8b,
	0x4b, 0x53, 0x73, 0x52, 0x75, 0xef, 0xe1, 0x53, 0xf8, 0x94, 0x92, 0x94, 0x2a, 0xca, 0x2e, 0xbf,
	0xef, 0xcf, 0x81, 0xff, 0x9c, 0x10, 0x0f, 0x45, 0x16, 0x56, 0x4a, 0x6a, 0x39, 0xba, 0xdf, 0x15,
	0x3a, 0xaf, 0xb3, 0x90, 0x4b, 0x11, 0xbd, 0xd4, 0x19, 0xa8, 0x12, 0x34, 0xe0, 0x8c, 0x63, 0x11,
	0x71, 0x2c, 0x66, 0x95, 0x92, 0x1f, 0x87, 0x88, 0x55, 0x45, 0x04, 0x4a, 0x49, 0x85, 0xcd, 0xd4,
	0xe4, 0xcb, 0x21, 0x17, 0x6b, 0x59, 0x97, 0x3a, 0x59, 0x2f, 0x92, 0x9c, 0x29, 0x88, 0xe1, 0xb5,
	0x06, 0xd4, 0xf4, 0x9a, 0xf8, 0x0a, 0x84, 0xd4, 0x90, 0xa2, 0xd1, 0x81, 0x33, 0x76, 0xa6, 0x5e,
	0xdc, 0x6f, 0x9c, 0x7d, 0x49, 0xaf, 0x88, 0x97, 0x4b, 0xd4, 0x69, 0xc5, 0x74, 0x1e, 0x9c, 0xd8,
	0xdc, 0x35, 0x62, 0xc3, 0x74, 0x4e, 0x47, 0xc4, 0x55, 0xc0, 0xb6, 0xb2, 0xdc, 0x1f, 0x82, 0xd3,
	0xb1, 0x33, 0x75, 0xe3, 0x1f, 0x36, 0x59, 0x8d, 0xa0, 0x4a, 0x26, 0x20, 0x38, 0x6b, 0xe6, 0x5a,
	0x36, 0x59, 0xc5, 0x10, 0xdf, 0xa5, 0xda, 0x06, 0xdd, 0x26, 0x6b, 0x79, 0xf2, 0xe9, 0x90, 0xe1,
	0xbf, 0xb2, 0x58, 0xc9, 0x12, 0x81, 0x06, 0xa4, 0x87, 0x35, 0xe7, 0x80, 0x68, 0x8b, 0xba, 0x71,
	0x8b, 0xf4, 0x96, 0xf8, 0x5c, 0x6c, 0xf7, 0xa0, 0x53, 0xbb, 0xb7, 0xed, 0xd9, 0x9f, 0xfb, 0xe1,
	0xd2, 0xca, 0x47, 0xe3, 0x56, 0x9d, 0xb8, 0xcf, 0x7f, 0x91, 0xde, 0x90, 0x81, 0x7d, 0x9b, 0x0a,
	0x40, 0x64, 0x3b, 0xb0, 0xfd, 0xbd, 0x55, 0x27, 0xf6, 0xad, 0x5e, 0x37, 0x76, 0xd1, 0x23, 0x5d,
	0xcb, 0xf3, 0x67, 0x42, 0x13, 0x91, 0x2d, 0x93, 0xa7, 0x8d, 0xb9, 0x71, 0x02, 0xea, 0xad, 0xe0,
	0x40, 0x1f, 0xc8, 0xe0, 0x4f, 0x57, 0x3a, 0x0c, 0x8f, 0x1d, 0x7a, 0x74, 0x19, 0x1e, 0x5d, 0x69,
	0xd2, 0xc9, 0xce, 0xed, 0x17, 0xdd, 0x7d, 0x07, 0x00, 0x00, 0xff, 0xff, 0x0a, 0x09, 0x0d, 0x05,
	0xe5, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// SmbCSIProxyServiceClient is the client API for SmbCSIProxyService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SmbCSIProxyServiceClient interface {
	// MountSMBShare mounts a remote share over SMB on the host at the requested global staging path.
	MountSMBShare(ctx context.Context, in *MountSMBShareRequest, opts ...grpc.CallOption) (*MountSMBShareResponse, error)
}

type smbCSIProxyServiceClient struct {
	cc *grpc.ClientConn
}

func NewSmbCSIProxyServiceClient(cc *grpc.ClientConn) SmbCSIProxyServiceClient {
	return &smbCSIProxyServiceClient{cc}
}

func (c *smbCSIProxyServiceClient) MountSMBShare(ctx context.Context, in *MountSMBShareRequest, opts ...grpc.CallOption) (*MountSMBShareResponse, error) {
	out := new(MountSMBShareResponse)
	err := c.cc.Invoke(ctx, "/SmbCSIProxyService/MountSMBShare", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SmbCSIProxyServiceServer is the server API for SmbCSIProxyService service.
type SmbCSIProxyServiceServer interface {
	// MountSMBShare mounts a remote share over SMB on the host at the requested global staging path.
	MountSMBShare(context.Context, *MountSMBShareRequest) (*MountSMBShareResponse, error)
}

// UnimplementedSmbCSIProxyServiceServer can be embedded to have forward compatible implementations.
type UnimplementedSmbCSIProxyServiceServer struct {
}

func (*UnimplementedSmbCSIProxyServiceServer) MountSMBShare(ctx context.Context, req *MountSMBShareRequest) (*MountSMBShareResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MountSMBShare not implemented")
}

func RegisterSmbCSIProxyServiceServer(s *grpc.Server, srv SmbCSIProxyServiceServer) {
	s.RegisterService(&_SmbCSIProxyService_serviceDesc, srv)
}

func _SmbCSIProxyService_MountSMBShare_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MountSMBShareRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SmbCSIProxyServiceServer).MountSMBShare(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/SmbCSIProxyService/MountSMBShare",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SmbCSIProxyServiceServer).MountSMBShare(ctx, req.(*MountSMBShareRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _SmbCSIProxyService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "SmbCSIProxyService",
	HandlerType: (*SmbCSIProxyServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "MountSMBShare",
			Handler:    _SmbCSIProxyService_MountSMBShare_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "smb.proto",
}
